import type { EvidenceClaim } from '../../../rules-platform/truth-model';
import { versioned } from '../records';
import { westernTmB4aBindingIds } from '../subjects/western-tm-b4a-special-hands';

const profile = { id: 'western-tm', version: '0.1' } as const;
const sourceId = 'tm-companion';
const title = 'Thompson & Maloney, The Mah Jong Player’s Companion';
const claim = (record: EvidenceClaim) => versioned(record.claimId, record);

export const westernTmB4aSpecialHandClaims = [
  claim({ claimId: "evidence.pattern.western-tm.wriggly-dragon", subjectId: "pattern.western-tm.wriggly-dragon", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 11, 31; Full Synopsis p. 56" }, status: 'verified', claim: "The complete one-suit 1–9 run is combined with one each of the three Dragons and a Dragon pair.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.wriggling-snake-any-pair", subjectId: "pattern.western-tm.wriggling-snake-any-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 10; Full Synopsis pp. 56\u201357" }, status: 'verified', claim: "A complete one-suit 1–9 run and all four Winds form a 13-tile base; any tile in that base may be duplicated to complete the hand.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.hachi-ban", subjectId: "pattern.western-tm.hachi-ban", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 10, 25, 30, 32" }, status: 'verified', claim: "One suit contributes a complete 1–8 or 2–9 run; the remaining six tiles are three distinct pairs, all Winds or all Dragons.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.suit-run-one-to-seven-with-winds-and-dragon-pung", subjectId: "pattern.western-tm.suit-run-one-to-seven-with-winds-and-dragon-pung", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 13; Full Synopsis pp. 56, 59" }, status: 'verified', claim: "complete loose 1–7 run, four Wind singles and one Dragon Pung", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.full-suit-run-with-dragon-singles-and-wind-pair", subjectId: "pattern.western-tm.full-suit-run-with-dragon-singles-and-wind-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail not illustrated; Full Synopsis p. 59" }, status: 'verified', claim: "complete loose 1–9 run, three Dragon singles and a Wind pair", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.two-suit-pairs-and-chows-one-two-five-six-nine", subjectId: "pattern.western-tm.two-suit-pairs-and-chows-one-two-five-six-nine", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 14, 50; Full Synopsis pp. 56, 60" }, status: 'verified', claim: "complete loose two-suit layout; either suit may carry either half", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.three-suit-chows-with-suited-meld-and-pair", subjectId: "pattern.western-tm.three-suit-chows-with-suited-meld-and-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 16; Full Synopsis p. 56" }, status: 'verified', claim: "grouped five-set shape; suited Pung/Kong and pair need not share a suit; represented Pung/Kong concealed-only", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.circle-chows-with-one-two-three-four-five-six-seven-eight-nine", subjectId: "pattern.western-tm.circle-chows-with-one-two-three-four-five-six-seven-eight-nine", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 15, 47; Full Synopsis pp. 56, 59" }, status: 'verified', claim: "grouped Circle-only four-Chow shape containing 123, 456 and 789", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.run-two-to-eight-with-one-and-nine-pungs", subjectId: "pattern.western-tm.run-two-to-eight-with-one-and-nine-pungs", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 9, 51; Full Synopsis p. 56" }, status: 'verified', claim: "2–8 run has its pair inside the run; 111 and 999 are in the other distinct suits", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.full-suit-run-with-five-distinct-honours", subjectId: "pattern.western-tm.full-suit-run-with-five-distinct-honours", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 11, 38; Full Synopsis p. 56" }, status: 'verified', claim: "exactly one 1–9 suit run and five distinct honours", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.suit-run-one-to-seven-with-all-honours", subjectId: "pattern.western-tm.suit-run-one-to-seven-with-all-honours", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 13, 38; Full Synopsis p. 56" }, status: 'verified', claim: "1–7 run plus every Wind and Dragon", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.run-one-to-nine-with-same-suit-pung-and-pair", subjectId: "pattern.western-tm.run-one-to-nine-with-same-suit-pung-and-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 9; Full Synopsis p. 56" }, status: 'verified', claim: "A single suit supplies Chows 123, 456 and 789, a Pung/Kong and a pair.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.run-one-to-nine-with-wind-pung-and-pair", subjectId: "pattern.western-tm.run-one-to-nine-with-wind-pung-and-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 10, 39; Full Synopsis p. 56" }, status: 'verified', claim: "A complete 1–9 run accompanies a Wind Pung/Kong and Wind pair.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.run-one-to-nine-with-dragon-pung-and-pair", subjectId: "pattern.western-tm.run-one-to-nine-with-dragon-pung-and-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 10\u201311, 39; Full Synopsis p. 56" }, status: 'verified', claim: "A complete 1–9 run accompanies a Dragon Pung/Kong and Dragon pair.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.run-one-to-nine-with-honour-pung-and-any-pair", subjectId: "pattern.western-tm.run-one-to-nine-with-honour-pung-and-any-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 11, 40; Full Synopsis p. 56" }, status: 'verified', claim: "A complete 1–9 run accompanies a Wind or Dragon Pung/Kong and any pair.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.full-suit-run-with-honour-pung-and-opposite-honour-pair", subjectId: "pattern.western-tm.full-suit-run-with-honour-pung-and-opposite-honour-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 12, 41; Full Synopsis pp. 56, 59" }, status: 'verified', claim: "ordinary five-set shape", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.four-chows-three-suits-one-two-one", subjectId: "pattern.western-tm.four-chows-three-suits-one-two-one", sourceId, locator: { kind: 'publication', title, year: 1997, page: "Full Synopsis p. 60 (not illustrated)" }, status: 'verified', claim: "four Chows and pair", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.western-gates-of-heaven", subjectId: "pattern.western-tm.western-gates-of-heaven", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 9, 47" }, status: 'verified', claim: "One suit forms 111, 999, one each of 2–8, and one duplicated middle tile; T&M completion semantics are distinct from the BMJA predicate.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.two-suit-runs-one-to-seven", subjectId: "pattern.western-tm.two-suit-runs-one-to-seven", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 14" }, status: 'verified', claim: "The loose layout contains one copy of each rank 1–7 in each of exactly two suits.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.north-south-wind-melds-with-1861-and-1865-two-suit-layout", subjectId: "pattern.western-tm.north-south-wind-melds-with-1861-and-1865-two-suit-layout", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 30" }, status: 'verified', claim: "North and South Pungs/Kongs combine with loose 1861 and 1865 layouts in different suits.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.two-to-eight-run-pair-with-terminal-meld-and-corresponding-dragon-meld", subjectId: "pattern.western-tm.two-to-eight-run-pair-with-terminal-meld-and-corresponding-dragon-meld", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 12, 34" }, status: 'verified', claim: "A 2–8 run and pair combine with a same-suit 1/9 Pung or Kong and corresponding Dragon Pung/Kong; the detail resolves the synopsis ambiguity.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.one-to-seven-run-pair-with-red-dragon-and-own-wind-melds", subjectId: "pattern.western-tm.one-to-seven-run-pair-with-red-dragon-and-own-wind-melds", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail pp. 13, 40" }, status: 'verified', claim: "A 1–7 run and pair combine with Red Dragon and player-own-Wind Pungs/Kongs; one-dot exposure halves value.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.three-suit-chows-with-mixed-chow-and-suited-pair", subjectId: "pattern.western-tm.three-suit-chows-with-mixed-chow-and-suited-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 15; Full Synopsis p. 56" }, status: 'verified', claim: "Three ordinary Chows, one in each suit, plus a suited pair and one loose Mixed Chow.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.four-mixed-chows-with-mixed-pair", subjectId: "pattern.western-tm.four-mixed-chows-with-mixed-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 16; Full Synopsis p. 56" }, status: 'verified', claim: "Four loose Mixed Chows and a Mixed Pair; the detailed entry fixes the half-limit treatment despite the synopsis discrepancy.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.white-dragon-meld-green-dragon-pair-with-three-mixed-chows", subjectId: "pattern.western-tm.white-dragon-meld-green-dragon-pair-with-three-mixed-chows", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 19; Full Synopsis pp. 56, 58" }, status: 'verified', claim: "A White Dragon Pung/Kong, Green Dragon pair and three Mixed Chows; the unmarked represented Dragon meld must remain concealed.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.three-mixed-chows-three-dragon-singles-own-wind-pair", subjectId: "pattern.western-tm.three-mixed-chows-three-dragon-singles-own-wind-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 19; Full Synopsis p. 56" }, status: 'verified', claim: "Three Mixed Chows, one of each Dragon and a pair of the player’s own Wind.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.two-suit-knitting", subjectId: "pattern.western-tm.two-suit-knitting", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 20; Full Synopsis p. 57" }, status: 'verified', claim: "Seven same-rank cross-suit pair units use exactly two suits; repeated ranks are allowed within tile-copy limits.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.three-suit-knitting-with-pair", subjectId: "pattern.western-tm.three-suit-knitting-with-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 20; Full Synopsis p. 57" }, status: 'verified', claim: "Four same-rank three-suit sets accompany a same-rank pair spanning two suits; repeated triplet ranks and overlap are allowed within tile-copy limits.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.three-four-tile-suit-runs-with-honour-pair", subjectId: "pattern.western-tm.three-four-tile-suit-runs-with-honour-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 14" }, status: 'verified', claim: "One consecutive four-tile run in each suit, with an honour pair; the three run starts differ.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.three-matching-four-tile-suit-runs-with-honour-pair", subjectId: "pattern.western-tm.three-matching-four-tile-suit-runs-with-honour-pair", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 14" }, status: 'verified', claim: "Matching consecutive four-tile runs in all three suits accompany an honour pair; this is the second mutually exclusive Big Robert variant.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.seven-pairs-all-from-wall", subjectId: "pattern.western-tm.seven-pairs-all-from-wall", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 22; Full Synopsis p. 57" }, status: 'verified', claim: "Seven distinct loose pairs; the winning tile is drawn from the wall, including the last wall tile.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.four-concealed-chows-one-suit-from-wall", subjectId: "pattern.western-tm.four-concealed-chows-one-suit-from-wall", sourceId, locator: { kind: 'publication', title, year: 1997, page: "detail p. 15; Full Synopsis pp. 56, 59" }, status: 'verified', claim: "Four concealed Chows and a same-suit pair, with the winning tile drawn from the wall including the last wall tile.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.four-winds-with-one-two-two-fours-three-sixes-four-eights", subjectId: "pattern.western-tm.four-winds-with-one-two-two-fours-three-sixes-four-eights", sourceId, locator: { kind: 'publication', title, year: 1997, page: "Full Synopsis p. 57 (not illustrated)" }, status: 'verified', claim: "All four Winds accompany a loose one-suit pattern of 2, 44, 666 and 8888; this is a complete 14-tile loose layout, not a declared Kong.", checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: "evidence.pattern.western-tm.four-winds-with-four-twos-three-fours-two-sixes-one-eight", subjectId: "pattern.western-tm.four-winds-with-four-twos-three-fours-two-sixes-one-eight", sourceId, locator: { kind: 'publication', title, year: 1997, page: "Full Synopsis p. 57 (not illustrated)" }, status: 'verified', claim: "All four Winds accompany a loose one-suit pattern of 2222, 444, 66 and 8; this is a complete 14-tile loose layout, not a declared Kong.", checkedOn: '2026-09-29', supportsProfile: profile }),
];
