import type { EvidenceClaim } from '../../../rules-platform/truth-model';
import { versioned } from '../records';
import { westernTmB4bBindingIds } from '../subjects/western-tm-b4b-pairs-winds';

const profile = { id: 'western-tm', version: '0.1' } as const;
const sourceId = 'tm-companion';
const title = 'Thompson & Maloney, The Mah Jong Player’s Companion';
const claim = (record: EvidenceClaim) => versioned(record.claimId, record);

export const westernTmB4bSpecialHandClaims = [
  claim({ claimId: 'evidence.pattern.western-tm.all-pair-honours', subjectId: 'pattern.western-tm.all-pair-honours', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 22, 44; synopsis pp. 57–58' }, status: 'verified', claim: 'Seven pairs are formed from Winds, Dragons, and/or suited terminals.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.four-blessings', subjectId: 'pattern.western-tm.four-blessings', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 30; synopsis p. 58' }, status: 'verified', claim: 'Four Wind Pungs/Kongs accompany a pair; the source exposure marker permits represented Wind melds to be exposed.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.wind-pair-with-three-suit-chows', subjectId: 'pattern.western-tm.wind-pair-with-three-suit-chows', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 18, 26; synopsis pp. 56–57' }, status: 'verified', claim: 'All four Winds are represented as one pair and three distinct singles, alongside a Chow in each suit.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.wind-pair-with-three-suit-one-two-three-chows', subjectId: 'pattern.western-tm.wind-pair-with-three-suit-one-two-three-chows', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 18, 26; synopsis pp. 56–57' }, status: 'verified', claim: 'All four Winds are represented as one pair and three distinct singles, alongside 123 Chows in all three suits.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.wind-pair-with-three-suit-seven-eight-nine-chows', subjectId: 'pattern.western-tm.wind-pair-with-three-suit-seven-eight-nine-chows', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 18, 26; synopsis pp. 56–57' }, status: 'verified', claim: 'All four Winds are represented as one pair and three distinct singles, alongside 789 Chows in all three suits.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.dragonette', subjectId: 'pattern.western-tm.dragonette', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 24, 39; synopsis p. 57' }, status: 'verified', claim: 'All four Winds, one pair, one single of each Dragon, and three non-terminal pairs from one suit form the layout.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.windfall', subjectId: 'pattern.western-tm.windfall', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 24, 27; synopsis p. 57' }, status: 'verified', claim: 'All four Winds accompany five pairs drawn from one suit.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.all-pair-ruby-jade', subjectId: 'pattern.western-tm.all-pair-ruby-jade', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 23, 32, 53; synopsis p. 57' }, status: 'verified', claim: 'Two pairs are the Green and Red Dragons; the remaining five pairs use red or green Bamboo ranks.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.four-bamboo-one-and-five-green-bamboo-pairs', subjectId: 'pattern.western-tm.four-bamboo-one-and-five-green-bamboo-pairs', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 21, 48, 53; synopsis p. 57' }, status: 'verified', claim: 'The pair layout uses four Bamboo 1 tiles and only the specified five green Bamboo pairs.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.seven-pairs-one-suit', subjectId: 'pattern.western-tm.seven-pairs-one-suit', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 21, 48; synopsis p. 57' }, status: 'verified', claim: 'Seven pairs use exactly one suit; honours are excluded.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.seven-pairs-one-suit-with-honours', subjectId: 'pattern.western-tm.seven-pairs-one-suit-with-honours', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 22; synopsis p. 57' }, status: 'verified', claim: 'Seven pairs use honours and at most one suited family; honours are optional.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.dragon-pair-with-five-suited-pairs', subjectId: 'pattern.western-tm.dragon-pair-with-five-suited-pairs', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 24, 31; synopsis p. 57' }, status: 'verified', claim: 'All three Dragons are represented by singles plus exactly one Dragon pair; five additional pairs use one suit.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.golden-gates', subjectId: 'pattern.western-tm.golden-gates', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 25; catalogue index §3' }, status: 'verified', claim: 'One suit supplies pairs of 2, 4, 6, and 8, plus a 1 or 9 Pung/Kong and its corresponding Dragon meld; either represented meld may be exposed.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.all-pair-green-dragon-and-bamboo', subjectId: 'pattern.western-tm.all-pair-green-dragon-and-bamboo', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 23, 32, 52; synopsis pp. 57, 60' }, status: 'verified', claim: 'Seven loose pairs use Green Dragons and Bamboo; the Green Dragon may occupy one or two pairs.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.four-wind-pairs-with-two-dragon-melds', subjectId: 'pattern.western-tm.four-wind-pairs-with-two-dragon-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 25, 46; synopsis pp. 57–58' }, status: 'verified', claim: 'Four Wind pairs accompany two Dragon melds; the source exposure markers permit represented Dragon melds to be exposed.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.wind-pair-with-three-suit-rank-one-melds', subjectId: 'pattern.western-tm.wind-pair-with-three-suit-rank-one-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 28, 45; synopsis p. 57' }, status: 'verified', claim: 'One rank-one suited Pung/Kong in each suit accompanies one Wind pair and three distinct Wind singles; the one-dot marker permits exposure of a represented suited meld.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.wind-pair-with-three-suit-rank-nine-melds', subjectId: 'pattern.western-tm.wind-pair-with-three-suit-rank-nine-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 28, 45; synopsis p. 57' }, status: 'verified', claim: 'One rank-nine suited Pung/Kong in each suit accompanies one Wind pair and three distinct Wind singles; the one-dot marker permits exposure of a represented suited meld.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.wind-pair-with-one-meld-in-each-suit', subjectId: 'pattern.western-tm.wind-pair-with-one-meld-in-each-suit', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 28; synopsis p. 57' }, status: 'verified', claim: 'All four Winds form one pair and three distinct singles, accompanying a Pung/Kong in each suit; no exposure marker is recorded, so represented melds remain concealed.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.wind-pair-with-three-suit-rank-three-melds', subjectId: 'pattern.western-tm.wind-pair-with-three-suit-rank-three-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 29; synopsis p. 57' }, status: 'verified', claim: 'One rank-three suited Pung/Kong in each suit accompanies one Wind pair and three distinct Wind singles; the one-dot marker permits exposure of a represented suited meld.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.wind-pair-with-three-suit-rank-seven-melds', subjectId: 'pattern.western-tm.wind-pair-with-three-suit-rank-seven-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 29; synopsis p. 57' }, status: 'verified', claim: 'One rank-seven suited Pung/Kong in each suit accompanies one Wind pair and three distinct Wind singles; the one-dot marker permits exposure of a represented suited meld.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.four-chows-three-suits-with-own-wind-pair', subjectId: 'pattern.western-tm.four-chows-three-suits-with-own-wind-pair', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 17; synopsis p. 56' }, status: 'verified', claim: 'Exactly four Chows cover Bamboo, Characters, and Circles, with a pair of the player’s own Wind, determined by seat/player Wind context.', checkedOn: '2026-09-29', supportsProfile: profile }),
] satisfies ReturnType<typeof claim>[];

if (westernTmB4bSpecialHandClaims.length !== westernTmB4bBindingIds.length) {
  throw new Error('B4B Western claim shard must contain one claim per selected binding.');
}
