import type { EvidenceClaim } from '../../../rules-platform/truth-model';
import { versioned } from '../records';
import { westernTmB4cBindingIds } from '../subjects/western-tm-b4c-dragons-honours-colours';

const profile = { id: 'western-tm', version: '0.1' } as const;
const sourceId = 'tm-companion';
const title = 'Thompson & Maloney, The Mah Jong Player’s Companion';
const claim = (record: EvidenceClaim) => versioned(record.claimId, record);

export const westernTmB4cSpecialHandClaims = [
  claim({ claimId: 'evidence.pattern.western-tm.all-winds-and-dragons', subjectId: 'pattern.western-tm.all-winds-and-dragons', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 46; synopsis p. 58' }, status: 'verified', claim: 'Four Pungs/Kongs and a pair use only Winds and Dragons; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.east-wind-meld-white-dragon-pair-three-suit-nonterminal-melds', subjectId: 'pattern.western-tm.east-wind-meld-white-dragon-pair-three-suit-nonterminal-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 42; synopsis pp. 58–59' }, status: 'verified', claim: 'An East Wind Pung/Kong and White Dragon pair accompany one non-terminal Pung/Kong in each suit; the one-dot marker permits exposure at a reduced treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.green-and-white-dragon-melds-with-green-bamboo', subjectId: 'pattern.western-tm.green-and-white-dragon-melds-with-green-bamboo', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 36, 52; synopsis pp. 58, 60' }, status: 'verified', claim: 'Green and White Dragon Pungs/Kongs accompany green Bamboo Pungs/Kongs and a green Bamboo pair; green Bamboo ranks are 2, 3, 4, 6, and 8. The two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.green-dragon-meld-with-green-bamboo-melds-and-pair-one-chow', subjectId: 'pattern.western-tm.green-dragon-meld-with-green-bamboo-melds-and-pair-one-chow', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 36; synopsis pp. 58, 60' }, status: 'verified', claim: 'A Green Dragon Pung/Kong, three green Bamboo melds, and a green Bamboo pair; at most one meld is a Chow, and that Chow must be Bamboo 234. The two-dot marker permits exposed Pungs/Kongs at the full treatment; an exposed permitted Chow alone does not reduce it.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.green-dragon-pung-white-dragon-pair-three-circle-melds', subjectId: 'pattern.western-tm.green-dragon-pung-white-dragon-pair-three-circle-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 36, 60; catalogue index Pass 4J' }, status: 'verified', claim: 'A Green Dragon Pung specifically, a White Dragon pair, and three Circle Pungs/Kongs; the one-dot marker permits exposure at a reduced treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.green-dragon-pung-with-bamboo-melds', subjectId: 'pattern.western-tm.green-dragon-pung-with-bamboo-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 35, 53; synopsis pp. 58, 60' }, status: 'verified', claim: 'A Green Dragon Pung specifically accompanies Bamboo Pungs/Kongs and a Bamboo pair; the source does not add a narrower red/green Bamboo distribution. The two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.green-dragon-pung-with-blue-circle-melds', subjectId: 'pattern.western-tm.green-dragon-pung-with-blue-circle-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'synopsis p. 60 (not illustrated)' }, status: 'verified', claim: 'A Green Dragon Pung specifically accompanies the source-defined blue Circle meld family and pair; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.heads-and-tails', subjectId: 'pattern.western-tm.heads-and-tails', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 45; synopsis p. 58' }, status: 'verified', claim: 'Four Pungs/Kongs and a pair use suited terminals only; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.one-suit-odd-melds', subjectId: 'pattern.western-tm.one-suit-odd-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 49; synopsis p. 59' }, status: 'verified', claim: 'Four Pungs/Kongs and a pair use odd ranks from one suit; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.own-wind-meld-with-dragon-pair-and-three-suit-chows', subjectId: 'pattern.western-tm.own-wind-meld-with-dragon-pair-and-three-suit-chows', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 17, 41; synopsis pp. 56, 59' }, status: 'verified', claim: 'One Chow in each suit accompanies a Pung/Kong of the player’s own Wind and a Dragon pair; an exposed own-Wind meld is ineligible.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.parallel-suit-rank-melds-with-honours', subjectId: 'pattern.western-tm.parallel-suit-rank-melds-with-honours', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 43; synopsis p. 59' }, status: 'verified', claim: 'Matching non-terminal Pungs/Kongs occur in each suit, alongside an honour Pung/Kong and an honour pair; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.red-and-green-dragon-melds-with-bamboo', subjectId: 'pattern.western-tm.red-and-green-dragon-melds-with-bamboo', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 37, 54; synopsis pp. 58, 60' }, status: 'verified', claim: 'Red and Green Dragon Pungs/Kongs accompany Bamboo Pungs/Kongs and a Bamboo pair; the source states no narrower Bamboo-rank distribution. The two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.red-and-green-dragon-pungs-with-three-suits', subjectId: 'pattern.western-tm.red-and-green-dragon-pungs-with-three-suits', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 34; synopsis p. 58' }, status: 'verified', claim: 'The Red Dragon and three suited groups are all Pungs, and the Green Dragon is a pair; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.red-and-white-dragon-melds-with-red-bamboo', subjectId: 'pattern.western-tm.red-and-white-dragon-melds-with-red-bamboo', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 37, 54; synopsis pp. 58, 60' }, status: 'verified', claim: 'Red and White Dragon Pungs/Kongs accompany red Bamboo Pungs/Kongs and a red Bamboo pair; red Bamboo ranks are 1, 5, 7, and 9. The two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.red-dragon-meld-with-red-bamboo-melds', subjectId: 'pattern.western-tm.red-dragon-meld-with-red-bamboo-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 37, 54; synopsis pp. 58, 60' }, status: 'verified', claim: 'A Red Dragon Pung/Kong accompanies red Bamboo Pungs/Kongs and a red Bamboo pair; red Bamboo ranks are 1, 5, 7, and 9. The two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.red-dragon-pung-with-character-melds', subjectId: 'pattern.western-tm.red-dragon-pung-with-character-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 35, 60; synopsis pp. 58, 60' }, status: 'verified', claim: 'A Red Dragon Pung specifically accompanies three Character Pungs/Kongs and a Character pair; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.red-dragon-pung-with-even-character-melds', subjectId: 'pattern.western-tm.red-dragon-pung-with-even-character-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'synopsis p. 60 (not illustrated)' }, status: 'verified', claim: 'A Red Dragon Pung specifically accompanies even Character Pungs/Kongs and an even Character pair; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.red-white-dragon-pungs-with-seven-tile-character-or-circle-run-pair', subjectId: 'pattern.western-tm.red-white-dragon-pungs-with-seven-tile-character-or-circle-run-pair', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 12, 33; synopsis pp. 56, 58' }, status: 'verified', claim: 'Red and White Dragon Pungs specifically accompany a seven-tile Character or Circle 1–7/2–8 run with one rank duplicated; the two-dot marker permits exposure without changing the hand treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.three-dragon-singles-with-one-meld-in-each-suit-and-suited-pair', subjectId: 'pattern.western-tm.three-dragon-singles-with-one-meld-in-each-suit-and-suited-pair', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 31; synopsis p. 58' }, status: 'verified', claim: 'One loose single of each Dragon accompanies a represented Pung/Kong in each suit and a suited pair; the one-dot marker permits exposure at a reduced treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.three-great-scholars', subjectId: 'pattern.western-tm.three-great-scholars', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 33; synopsis p. 58' }, status: 'verified', claim: 'A Pung/Kong of each of the three Dragons is present with the remaining set and pair structure.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.two-odd-suits-and-one-even-suit', subjectId: 'pattern.western-tm.two-odd-suits-and-one-even-suit', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'synopsis p. 60 (not illustrated)' }, status: 'verified', claim: 'The complete loose layout uses odd ranks in two suits and even ranks in the third suit.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.two-ranks-doubled-across-two-suits-with-honour-pair', subjectId: 'pattern.western-tm.two-ranks-doubled-across-two-suits-with-honour-pair', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 43, 59' }, status: 'verified', claim: 'Two non-terminal ranks each form Pungs/Kongs in both of two suits, accompanied by an honour pair; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.white-dragon-meld-red-dragon-pair-three-suit-nonterminal-melds', subjectId: 'pattern.western-tm.white-dragon-meld-red-dragon-pair-three-suit-nonterminal-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail p. 42; synopsis pp. 58–59' }, status: 'verified', claim: 'A White Dragon Pung/Kong and Red Dragon pair accompany one non-terminal Pung/Kong in each suit; the one-dot marker permits exposure at a reduced treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.white-dragon-meld-with-even-circle-melds', subjectId: 'pattern.western-tm.white-dragon-meld-with-even-circle-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'synopsis p. 60 (not illustrated)' }, status: 'verified', claim: 'A White Dragon Pung/Kong accompanies even Circle Pungs/Kongs and an even Circle pair; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.white-dragon-pung-with-circle-melds', subjectId: 'pattern.western-tm.white-dragon-pung-with-circle-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'detail pp. 35, 60; synopsis pp. 58, 60' }, status: 'verified', claim: 'A White Dragon Pung specifically accompanies three Circle Pungs/Kongs and a Circle pair; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
  claim({ claimId: 'evidence.pattern.western-tm.white-dragon-pung-with-odd-character-melds', subjectId: 'pattern.western-tm.white-dragon-pung-with-odd-character-melds', sourceId, locator: { kind: 'publication', title, year: 1997, page: 'synopsis p. 60 (not illustrated)' }, status: 'verified', claim: 'A White Dragon Pung specifically accompanies odd Character Pungs/Kongs and an odd Character pair; the two-dot marker permits represented meld exposure at the full treatment.', checkedOn: '2026-09-29', supportsProfile: profile }),
] satisfies ReturnType<typeof claim>[];

if (westernTmB4cSpecialHandClaims.length !== westernTmB4cBindingIds.length) {
  throw new Error('B4C Western claim shard must contain one claim per frozen binding.');
}
