import { useMemo, useState } from 'react';
import { RulesProfilePicker } from './RulesProfilePicker';
import { toMcrScoringInput } from './mcr-hand-input';
import { presentMcrScore } from './mcr-score-presentation';
import { getCurrentCompiledRulesRuntime } from '../rules-platform/current-runtime-registry';
import { bonus, dragon, expandedTiles, set, suited, wind } from '../scoring/tiles';
import type { BonusTile, HandSet, PlayingTile, Suit, Wind, MahjongHand } from '../scoring/types';
import type { McrResolvedWinEvent, McrWinSource, McrWind } from '../rules-platform/mcr-scoring-input';
import type { RulesProfileRef } from './types';

const profile = { id: 'mcr-wmo-2006', version: '0.1' };
const faces: PlayingTile[] = [
  ...(['characters', 'bamboo', 'circles'] as Suit[]).flatMap((suit) => Array.from({ length: 9 }, (_, i) => suited(suit, (i + 1) as 1|2|3|4|5|6|7|8|9))),
  ...(['east', 'south', 'west', 'north'] as Wind[]).map(wind),
  ...(['red', 'green', 'white'] as const).map(dragon),
];
const key = (tile: PlayingTile) => tile.family === 'suit' ? `${tile.suit}:${tile.rank}` : tile.family === 'wind' ? `wind:${tile.wind}` : `dragon:${tile.dragon}`;
const label = (tile: PlayingTile) => tile.family === 'suit' ? `${tile.rank} ${tile.suit}` : tile.family === 'wind' ? `${tile.wind} wind` : `${tile.dragon} dragon`;
const eventOptions: readonly { value: McrResolvedWinEvent; label: string; source?: McrWinSource }[] = [
  { value: 'none', label: 'Normal win' }, { value: 'last-wall-draw', label: 'Last wall draw', source: 'self-draw' },
  { value: 'last-discard', label: 'Last discard', source: 'discard' }, { value: 'kong-replacement', label: 'Kong replacement', source: 'self-draw' },
  { value: 'flower-replacement', label: 'Flower replacement', source: 'self-draw' }, { value: 'rob-kong', label: 'Robbing a Kong', source: 'discard' },
];
const winds = ['east', 'south', 'west', 'north'] as const;

export function McrStandaloneHandScorer({ selectedProfile, onProfileChange, onClose }: { selectedProfile: RulesProfileRef; onProfileChange: (profile: RulesProfileRef) => void; onClose: () => void }) {
  const [groups, setGroups] = useState<HandSet[]>([]);
  const [loose, setLoose] = useState<PlayingTile[]>([]);
  const [kind, setKind] = useState<HandSet['kind']>('pung');
  const [visibility, setVisibility] = useState<HandSet['visibility']>('concealed');
  const [tileKey, setTileKey] = useState(key(faces[0]!));
  const [target, setTarget] = useState<{ type: 'grouped-set'; setId: string; tile: PlayingTile; tileIndex: number } | { type: 'loose-layout'; index: number; tile: PlayingTile }>();
  const [source, setSource] = useState<McrWinSource>();
  const [event, setEvent] = useState<McrResolvedWinEvent>();
  const [lastVisible, setLastVisible] = useState<boolean | undefined>();
  const [seatWind, setSeatWind] = useState<McrWind>();
  const [prevailingWind, setPrevailingWind] = useState<McrWind>();
  const [bonusKeys, setBonusKeys] = useState<string[]>([]);
  const chosenTile = faces.find((tile) => key(tile) === tileKey)!;
  const hand: MahjongHand = useMemo(() => ({ sets: groups, looseTiles: loose, bonusTiles: bonusKeys.map((entry) => { const [family, number] = entry.split(':'); return bonus(family as BonusTile['family'], Number(number) as BonusTile['number']); }), isWinner: true, winningTileProvenance: target ? { tile: target.tile, target: target.type === 'grouped-set' ? { type: 'grouped-set', setId: target.setId, ...(groups.find(({ id }) => id === target.setId)?.kind === 'chow' ? { tileIndex: target.tileIndex as 0|1|2 } : {}) } : { type: 'loose-layout' } } : undefined }), [groups, loose, bonusKeys, target]);
  const adapted = source && event ? toMcrScoringInput(hand, { winSource: source, resolvedWinEvent: event, lastVisibleCopy: lastVisible, seatWind, prevailingWind }) : { kind: 'winning-tile-required' as const };
  const compiled = getCurrentCompiledRulesRuntime(profile);
  const view = adapted.kind === 'ready' && compiled.grammar === 'pattern-accumulator' ? presentMcrScore(compiled.runtime.scoreHand(adapted.input)) : undefined;
  const toggleBonus = (id: string) => setBonusKeys((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const addGroup = () => { const next = set(`mcr-group-${Date.now()}`, kind, chosenTile, visibility); setGroups((current) => [...current, next]); setTarget(undefined); };
  const addLoose = () => { setLoose((current) => [...current, chosenTile]); setTarget(undefined); };
  return <div className="mahjong-shell min-h-screen"><main className="mx-auto max-w-[1100px] px-5 py-8 lg:px-8"><header className="mb-6"><p className="font-mono text-[11px] uppercase tracking-widest text-[#ae6249]">Standalone winning-hand scorer</p><h1 className="mt-2 font-serif text-4xl text-[#284d45]">Mahjong Competition Rules</h1><p className="mt-3 text-sm leading-6 text-[#66746e]">Enter a completed winning hand. MCR scoring uses fan, an 8-point qualifying minimum before Flowers, and Basic Points.</p><button type="button" onClick={onClose} className="mt-3 underline">Leave scorer</button></header>
    <RulesProfilePicker surface="hand" prompt="Which rules are you scoring?" selectedProfile={selectedProfile} onSelect={onProfileChange} />
    <section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-5 rounded-xl border border-[#d8ceb8] bg-[#fbf8ed] p-5"><h2 className="font-serif text-2xl text-[#284d45]">Winning hand tiles</h2><p className="text-sm text-[#66746e]">This scorer represents a completed winning hand. Choose the physical group layout; concealed groups are left for the MCR interpretation resolver.</p>
      <div className="grid gap-3 sm:grid-cols-3"><label className="text-xs">Group<select value={kind} onChange={(e) => setKind(e.target.value as HandSet['kind'])} className="mt-1 w-full rounded border p-2"><option value="chow">Chow</option><option value="pung">Pung</option><option value="kong">Kong</option><option value="pair">Pair</option></select></label><label className="text-xs">Visibility<select value={visibility} onChange={(e) => setVisibility(e.target.value as HandSet['visibility'])} className="mt-1 w-full rounded border p-2"><option value="concealed">Concealed</option><option value="exposed">Exposed</option></select></label><label className="text-xs">Tile face<select value={tileKey} onChange={(e) => setTileKey(e.target.value)} className="mt-1 w-full rounded border p-2">{faces.map((tile) => <option key={key(tile)} value={key(tile)}>{label(tile)}</option>)}</select></label></div><div className="flex flex-wrap gap-2"><button type="button" onClick={addGroup} className="rounded bg-[#284d45] px-3 py-2 text-sm text-white">Add physical group</button><button type="button" onClick={addLoose} className="rounded border px-3 py-2 text-sm">Add loose tile</button></div>
      <ul className="space-y-2">{groups.map((group) => <li key={group.id} className="flex items-center justify-between gap-3 rounded border bg-white p-3 text-sm"><span>{group.kind} · {group.visibility} · {label(group.tile)}</span><span className="flex flex-wrap justify-end gap-2">{expandedTiles(group).map((tile, tileIndex) => <button type="button" key={`${key(tile)}-${tileIndex}`} aria-label={`Record ${label(tile)} from ${group.kind} as winning tile`} onClick={() => setTarget({ type: 'grouped-set', setId: group.id, tile, tileIndex })} className="underline">Win {label(tile)}</button>)}<button type="button" aria-label="Remove group" onClick={() => { setGroups((current) => current.filter(({ id }) => id !== group.id)); if (target?.type === 'grouped-set' && target.setId === group.id) setTarget(undefined); }}>Remove</button></span></li>)}</ul>
      <ul className="space-y-2">{loose.map((tile, index) => <li key={`${key(tile)}-${index}`} className="flex justify-between rounded border bg-white p-3 text-sm"><span>Loose · {label(tile)}</span><span className="flex gap-2"><button type="button" onClick={() => setTarget({ type: 'loose-layout', index, tile })} className="underline">Winning tile</button><button type="button" aria-label="Remove loose tile" onClick={() => { setLoose((current) => current.filter((_, i) => i !== index)); setTarget(undefined); }}>Remove</button></span></li>)}</ul>
      <fieldset><legend className="mb-2 text-sm font-semibold">Flowers and Seasons</legend><div className="flex flex-wrap gap-3">{(['flower','season'] as const).flatMap((family) => [1,2,3,4].map((number) => { const id = `${family}:${number}`; return <label key={id} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={bonusKeys.includes(id)} onChange={() => toggleBonus(id)} />{family === 'flower' ? 'Flower' : 'Season'} {number}</label>; }))}</div></fieldset>
    </div><aside className="space-y-5"><section className="rounded-xl border border-[#d8ceb8] bg-[#fbf8ed] p-5"><h2 className="font-serif text-2xl text-[#284d45]">Scoring evidence</h2><label className="mt-3 block text-sm">Win source<select value={source ?? ''} onChange={(e) => { const next = (e.target.value || undefined) as McrWinSource | undefined; setSource(next); if (eventOptions.find((item) => item.value === event)?.source && eventOptions.find((item) => item.value === event)?.source !== next) setEvent(undefined); }} className="mt-1 w-full rounded border p-2"><option value="">Choose win source</option><option value="discard">Claimed from discard</option><option value="self-draw">Self-drawn</option></select></label><label className="mt-3 block text-sm">Resolved win event<select value={event ?? ''} onChange={(e) => setEvent((e.target.value || undefined) as McrResolvedWinEvent | undefined)} className="mt-1 w-full rounded border p-2"><option value="">Choose resolved event</option>{eventOptions.filter((item) => !item.source || item.source === source).map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="mt-3 block text-sm">Last visible copy<select value={lastVisible === undefined ? 'unknown' : String(lastVisible)} onChange={(e) => setLastVisible(e.target.value === 'unknown' ? undefined : e.target.value === 'true')} className="mt-1 w-full rounded border p-2"><option value="unknown">Unknown</option><option value="true">Yes</option><option value="false">No</option></select></label><label className="mt-3 block text-sm">Seat wind<select value={seatWind ?? ''} onChange={(e) => setSeatWind((e.target.value || undefined) as McrWind | undefined)} className="mt-1 w-full rounded border p-2"><option value="">Not entered</option>{winds.map((value) => <option key={value}>{value}</option>)}</select></label><label className="mt-3 block text-sm">Prevailing wind<select value={prevailingWind ?? ''} onChange={(e) => setPrevailingWind((e.target.value || undefined) as McrWind | undefined)} className="mt-1 w-full rounded border p-2"><option value="">Not entered</option>{winds.map((value) => <option key={value}>{value}</option>)}</select></label></section>
      <section data-testid="mcr-score-result" className="rounded-xl border border-[#b8cdbf] bg-[#edf3ed] p-5"><h2 className="font-serif text-2xl text-[#284d45]">MCR result</h2>{!source || !event ? <><p className="mt-3 font-semibold">More evidence is needed before a final score.</p><ul className="mt-2 list-disc pl-5 text-sm">{!source && <li data-evidence-id="evidence.winning-method">Choose whether the win was self-drawn or claimed from a discard.</li>}{!event && <li data-evidence-id="evidence.resolved-win-event">Choose the resolved win event, including Normal win when applicable.</li>}</ul></> : adapted.kind === 'winning-tile-required' ? <p className="mt-3 text-sm">Identify the recorded winning tile before scoring.</p> : !view ? <p className="mt-3 text-sm">This profile’s compiled scoring runtime is unavailable.</p> : view.kind === 'needs-evidence' ? <><p className="mt-3 font-semibold">More evidence is needed before a final score.</p><ul className="mt-2 list-disc pl-5 text-sm">{view.prompts.map(({ id, prompt }) => <li key={id} data-evidence-id={id}>{prompt}</li>)}</ul></> : view.kind === 'not-qualifying' ? <p className="mt-3 text-sm">This hand is below the 8-point minimum before Flowers. Flowers cannot rescue a hand below the minimum.</p> : view.kind === 'invalid' ? <p className="mt-3 text-sm">Invalid / not scoreable ({view.reasonId}).</p> : <><div className="mt-4"><p className="text-sm">Qualifying subtotal: <strong>{view.qualifyingSubtotal}</strong></p><p className="text-sm">Flowers: <strong>{view.flowers}</strong></p><p className="mt-2 text-3xl font-semibold">{view.basicPoints} Basic Points</p></div><h3 className="mt-4 font-semibold">Counted fan</h3><ul className="text-sm">{view.counted.map((fan) => <li key={`${fan.name}-${fan.sourceLocator}`}>{fan.name} · {fan.value} <span className="text-xs">{fan.sourceLocator}</span></li>)}</ul>{view.suppressed.length > 0 && <><h3 className="mt-4 font-semibold">Suppressed fan</h3><ul className="text-sm">{view.suppressed.map((fan) => <li key={`${fan.name}-${fan.reasonId}`}>{fan.name} · {fan.value} — {fan.reason} <span className="text-xs">{fan.sourceLocator}</span></li>)}</ul></>}</>}</section></aside></section></main></div>;
}
