import type { SpecialHandPatternBinding } from "../scoring/special-hands";
import type { RulesProfileRef } from "./types";

export const WESTERN_TM_PROFILE_REF: RulesProfileRef = Object.freeze({
  id: "western-tm",
  version: "0.1",
});

export const westernTmSpecialHandBindings: SpecialHandPatternBinding[] = [
  {
    patternId: "three-great-scholars",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Three Great Scholars",
    description: "A pung or kong of each of the three dragons.",
    value: 1500,
    fishingValue: 600,
  },
  {
    patternId: "thirteen-unique-wonders",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Unique Wonder",
    description:
      "One of every terminal, wind and dragon, plus a pair of any one.",
    value: 2000,
    fishingValue: 800,
  },
  {
    patternId: "all-pair-honours",
    profile: WESTERN_TM_PROFILE_REF,
    name: "All Pair Honours",
    description:
      "Seven pairs of major tiles: 1s, 9s, winds and dragons; repeated pairs are allowed.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "four-blessings",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Four Blessings",
    description: "A pung or kong of each wind, plus any pair.",
    value: 1500,
    fishingValue: 600,
  },
  {
    patternId: "all-winds-and-dragons",
    profile: WESTERN_TM_PROFILE_REF,
    name: "All Winds and Dragons",
    description:
      "Four pungs/kongs and a pair, all made from winds and dragons.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "heads-and-tails",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Heads and Tails",
    description: "Four pungs/kongs and a pair, all made from suited 1s and 9s.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "wriggly-dragon",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Wriggly Dragon",
    description:
      "Three Dragon singles plus a Dragon pair, and a suited run from 1 through 9.",
    value: 1000,
    fishingValue: 400,
  },
  { patternId: "suit-run-one-to-seven-with-winds-and-dragon-pung", profile: WESTERN_TM_PROFILE_REF, name: "Greta's Dragon", description: "A 1–7 run in one suit, all four Winds and a Dragon Pung.", value: 1000, fishingValue: 400 },
  { patternId: "full-suit-run-with-dragon-singles-and-wind-pair", profile: WESTERN_TM_PROFILE_REF, name: "Dragon's Run", description: "A 1–9 run in one suit, one of each Dragon and a Wind pair.", value: 1500, fishingValue: 600 },
  { patternId: "two-suit-pairs-and-chows-one-two-five-six-nine", profile: WESTERN_TM_PROFILE_REF, name: "Yin Yang", description: "Two suits: 11, 234, 55 in one; 55, 678, 99 in the other.", value: 1000, fishingValue: 400 },
  { patternId: "three-suit-chows-with-suited-meld-and-pair", profile: WESTERN_TM_PROFILE_REF, name: "Little Robert", description: "One Chow in each suit, a suited Pung/Kong and a suited pair.", value: 500, fishingValue: 200, exposure: { allowed: false } },
  { patternId: "circle-chows-with-one-two-three-four-five-six-seven-eight-nine", profile: WESTERN_TM_PROFILE_REF, name: "Moon at Bottom of Well", description: "Four Circle Chows and a Circle pair, including 123, 456 and 789.", value: 1000, fishingValue: 400 },
  { patternId: "wind-pair-with-three-suit-chows", profile: WESTERN_TM_PROFILE_REF, name: "Windy Chow", description: "A pair and singles of the four Winds, plus one Chow in each suit.", value: 500, fishingValue: 200 },
  { patternId: "wind-pair-with-three-suit-one-two-three-chows", profile: WESTERN_TM_PROFILE_REF, name: "Chop Suey", description: "A Wind pair and singles, plus 123 Chows in each suit.", value: 500, fishingValue: 200 },
  { patternId: "wind-pair-with-three-suit-seven-eight-nine-chows", profile: WESTERN_TM_PROFILE_REF, name: "Chow Mein", description: "A Wind pair and singles, plus 789 Chows in each suit.", value: 500, fishingValue: 200 },
  {
    patternId: "wriggling-snake-any-pair",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Wriggly Snake",
    description:
      "A suited run from 1 through 9, one of each Wind, and a pair of any one of those tiles.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "hachi-ban",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Hachi Ban",
    description:
      "A suited run from 1 through 8 or 2 through 9, plus three pairs of Winds or Dragons.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "dragonette",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Dragonette",
    description:
      "One of each Wind, a Dragon pair with the other Dragons single, and three non-terminal pairs in one suit.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "windfall",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Windfall",
    description: "One of each Wind and five pairs in one suit.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "all-pair-ruby-jade",
    profile: WESTERN_TM_PROFILE_REF,
    name: "All Pair Ruby Jade",
    description:
      "Pairs of Green and Red Dragons plus five pairs of red or green Bamboo ranks.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "run-two-to-eight-with-one-and-nine-pungs",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Confused Gates",
    description:
      "A 2–8 run with one paired tile, plus 111 and 999 in the other two suits.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "full-suit-run-with-five-distinct-honours",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Five Odd Honours",
    description: "A 1–9 run in one suit and five distinct Winds or Dragons.",
    value: 500,
    fishingValue: 200,
  },
  {
    patternId: "suit-run-one-to-seven-with-all-honours",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Greta's Garden",
    description: "A 1–7 run in one suit, all four Winds and all three Dragons.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "four-bamboo-one-and-five-green-bamboo-pairs",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Sparrow's Sanctuary",
    description:
      "All four Bamboo 1 tiles and pairs of Bamboo 2, 3, 4, 6 and 8.",
    value: 1500,
    fishingValue: 600,
  },
  {
    patternId: "seven-pairs-one-suit",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Heavenly Twins",
    description: "Seven pairs, all in one suit.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "seven-pairs-one-suit-with-honours",
    profile: WESTERN_TM_PROFILE_REF,
    name: "All Pair",
    description:
      "Seven pairs using at most one suit, with Winds and Dragons allowed.",
    value: 500,
    fishingValue: 200,
  },
  {
    patternId: "dragon-pair-with-five-suited-pairs",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Dragon's Breath",
    description:
      "A pair and singles of all three Dragons, plus five pairs in one suit.",
    value: 1000,
    fishingValue: 400,
  },
  {
    patternId: "purity-one-chow",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Purity",
    description: "One suit, four melds and a pair; one meld may be a chow.",
    scoreModel: {
      kind: "calculated",
      exposure: {
        multiplier: 0.5,
        triggerSetKinds: ["pung", "kong"],
        forbiddenSetKinds: ["chow"],
      },
    },
  },
  {
    patternId: "golden-gates",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Golden Gates",
    description:
      "Pairs of 2, 4, 6 and 8 in one suit, with its 1 or 9 and corresponding Dragon as Pungs or Kongs.",
    value: 1000,
    fishingValue: 400,
    exposure: { allowed: true, exposedValue: 500, exposedFishingValue: 200 },
  },
  {
    patternId: "run-one-to-nine-with-same-suit-pung-and-pair",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Run, Pung & Pair",
    description:
      "A 1–9 run as three chows, with a Pung/Kong and pair in the same suit.",
    value: 1000,
    fishingValue: 400,
    exposure: { allowed: false },
  },
  {
    patternId: "run-one-to-nine-with-wind-pung-and-pair",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Guardian Winds",
    description: "A 1–9 run, plus a Wind Pung/Kong and Wind pair.",
    value: 1000,
    fishingValue: 400,
    exposure: { allowed: false },
  },
  {
    patternId: "run-one-to-nine-with-dragon-pung-and-pair",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Guardian Dragons",
    description: "A 1–9 run, plus a Dragon Pung/Kong and Dragon pair.",
    value: 1000,
    fishingValue: 400,
    exposure: { allowed: false },
  },
  {
    patternId: "run-one-to-nine-with-honour-pung-and-any-pair",
    profile: WESTERN_TM_PROFILE_REF,
    name: "Grand Sequence",
    description: "A 1–9 run, an honour Pung/Kong, and any pair.",
    value: 1000,
    fishingValue: 400,
    exposure: { allowed: false },
  },
  { patternId: "full-suit-run-with-honour-pung-and-opposite-honour-pair", profile: WESTERN_TM_PROFILE_REF, name: "Dragon's Tail", description: "A 1–9 run, a Wind Pung/Kong and Dragon pair, or the reverse.", value: 1000, fishingValue: 400, exposure: { allowed: true, exposedValue: 500, exposedFishingValue: 200 } },
  { patternId: "all-pair-green-dragon-and-bamboo", profile: WESTERN_TM_PROFILE_REF, name: "All Pair Jade", description: "Seven pairs of Green Dragons and green Bamboo tiles.", value: 1000, fishingValue: 400 },
  { patternId: "four-wind-pairs-with-two-dragon-melds", profile: WESTERN_TM_PROFILE_REF, name: "Windy Dragons", description: "Pairs of every Wind and two Dragon Pungs/Kongs.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: "red-dragon-pung-with-character-melds", profile: WESTERN_TM_PROFILE_REF, name: "Red Coral", description: "A Red Dragon Pung, three Character Pungs/Kongs and a Character pair.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: "white-dragon-pung-with-circle-melds", profile: WESTERN_TM_PROFILE_REF, name: "White Opal", description: "A White Dragon Pung, three Circle Pungs/Kongs and a Circle pair.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: "one-suit-odd-melds", profile: WESTERN_TM_PROFILE_REF, name: "Chinese Odds", description: "Four Pungs/Kongs and a pair of odd ranks in one suit.", value: 500, fishingValue: 200, exposure: { allowed: true } },
  { patternId: "two-odd-suits-and-one-even-suit", profile: WESTERN_TM_PROFILE_REF, name: "Odds & Evens", description: "Odd ranks in two suits and even ranks in the third.", value: 1000, fishingValue: 400 },
  { patternId: "four-chows-three-suits-one-two-one", profile: WESTERN_TM_PROFILE_REF, name: "Robin", description: "Four Chows across all three suits in a 1/2/1 distribution and a pair.", value: 500, fishingValue: 200 },
  { patternId: "parallel-suit-rank-melds-with-honours", profile: WESTERN_TM_PROFILE_REF, name: "Numbers in Parallel", description: "Matching non-terminal Pungs/Kongs in each suit plus an honour Pung/Kong and pair.", value: 1500, fishingValue: 600, exposure: { allowed: true } },
  { patternId: "green-dragon-pung-with-blue-circle-melds", profile: WESTERN_TM_PROFILE_REF, name: "Blue Mountains", description: "A Green Dragon Pung with blue Circle Pungs/Kongs and pair.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: "white-dragon-meld-with-even-circle-melds", profile: WESTERN_TM_PROFILE_REF, name: "White Elephant", description: "A White Dragon Pung/Kong with even Circle Pungs/Kongs and pair.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: "white-dragon-pung-with-odd-character-melds", profile: WESTERN_TM_PROFILE_REF, name: "Driven Snow", description: "A White Dragon Pung with odd Character Pungs/Kongs and pair.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: "red-dragon-pung-with-even-character-melds", profile: WESTERN_TM_PROFILE_REF, name: "Dragon's Scales", description: "A Red Dragon Pung with even Character Pungs/Kongs and pair.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: "green-dragon-pung-with-bamboo-melds", profile: WESTERN_TM_PROFILE_REF, name: "Green Jade", description: "A Green Dragon Pung with Bamboo Pungs/Kongs and a Bamboo pair.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: "green-and-white-dragon-melds-with-green-bamboo", profile: WESTERN_TM_PROFILE_REF, name: "Lily of the Valley", description: "Green and White Dragon Pungs/Kongs with green Bamboo Pungs/Kongs and pair.", value: 2000, fishingValue: 800, exposure: { allowed: true } },
  { patternId: "red-and-green-dragon-pungs-with-three-suits", profile: WESTERN_TM_PROFILE_REF, name: "Red Waratah", description: "Red Dragon, red Bamboo, Circle and Character Pungs with a Green Dragon pair.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: "red-dragon-meld-with-red-bamboo-melds", profile: WESTERN_TM_PROFILE_REF, name: "Royal Ruby", description: "A Red Dragon Pung/Kong with red Bamboo Pungs/Kongs and pair.", value: 2000, fishingValue: 800, exposure: { allowed: true } },
  { patternId: "red-and-white-dragon-melds-with-red-bamboo", profile: WESTERN_TM_PROFILE_REF, name: "Red Lily", description: "Red and White Dragon Pungs/Kongs with red Bamboo Pungs/Kongs and pair.", value: 2000, fishingValue: 800, exposure: { allowed: true } },
  { patternId: "red-and-green-dragon-melds-with-bamboo", profile: WESTERN_TM_PROFILE_REF, name: "Ruby Jade", description: "Red and Green Dragon Pungs/Kongs with Bamboo Pungs/Kongs and pair.", value: 1000, fishingValue: 400, exposure: { allowed: true } },
  { patternId: 'wind-pair-with-three-suit-rank-one-melds', profile: WESTERN_TM_PROFILE_REF, name: 'Windy Ones', description: 'A Pung/Kong of 1s in each suit, with a Wind pair and the other Winds single.', value: 1000, fishingValue: 400, exposure: { allowed: true, exposedValue: 500, exposedFishingValue: 200 } },
  { patternId: 'wind-pair-with-three-suit-rank-nine-melds', profile: WESTERN_TM_PROFILE_REF, name: 'Windy Nines', description: 'A Pung/Kong of 9s in each suit, with a Wind pair and the other Winds single.', value: 1000, fishingValue: 400, exposure: { allowed: true, exposedValue: 500, exposedFishingValue: 200 } },
  { patternId: 'wind-pair-with-one-meld-in-each-suit', profile: WESTERN_TM_PROFILE_REF, name: 'Windvane', description: 'A Pung/Kong in each suit, with a Wind pair and the other Winds single.', value: 1000, fishingValue: 400, exposure: { allowed: false } },
  { patternId: 'wind-pair-with-three-suit-rank-three-melds', profile: WESTERN_TM_PROFILE_REF, name: 'Three Sisters', description: 'A Pung/Kong of 3s in each suit, with a Wind pair and the other Winds single.', value: 1000, fishingValue: 400, exposure: { allowed: true, exposedValue: 500, exposedFishingValue: 200 } },
  { patternId: 'wind-pair-with-three-suit-rank-seven-melds', profile: WESTERN_TM_PROFILE_REF, name: 'Seven Brothers', description: 'A Pung/Kong of 7s in each suit, with a Wind pair and the other Winds single.', value: 1000, fishingValue: 400, exposure: { allowed: true, exposedValue: 500, exposedFishingValue: 200 } },
];
