import { describe, expect, it } from 'vitest';
import {
  architectureSeedEntries, assertFamilyCompatibility, inspectProfile, RegistryBank, resolvePlayableProfile,
  type JsonContract, type JsonObject, type ProfileAuthoringDefinition, type ResolverEnvironment,
  type RootProfileDefinition, type RulesFamilyDefinition, type ScoringGrammarId,
} from './index';

type Fixture = {
  id: string;
  definition: RootProfileDefinition;
  family: RulesFamilyDefinition;
  expectedCategories: Readonly<Record<string, string>>;
};

const source = (id: string) => `source.${id}`;
const strategy = (id: string, params: JsonObject = {}) => ({ id, params });
const root = (id: string, familyId: string, grammar: ScoringGrammarId, table: JsonObject, tileSet: JsonObject, handShape: JsonObject, validation: JsonObject, scoring: JsonObject, evidence: JsonObject, settlement: string, progression: string, gameEnd: string, sourceId: string, settlementParams: JsonObject = {}): RootProfileDefinition => ({
  kind: 'root', schemaVersion: 1, identity: { id, version: 'architecture-1', name: id, status: 'provisional' },
  definition: { familyId, grammar, table, tileSet, handShape, validation, scoring: { grammar, config: scoring }, evidence, settlement: strategy(settlement, settlementParams), progression: strategy(progression), gameEnd: strategy(gameEnd), provenance: { sources: [sourceId], metadata: { fixture: id } } },
});

const accumulator = (unit: 'fan' | 'points' | 'tai', patternCatalogueId: string, interactionPolicyId: string, qualificationPolicyId: string, extra: JsonObject = {}) => ({ configVersion: 1, unit, patternCatalogueId, interactionPolicyId, qualificationPolicyId, interpretationPolicyId: 'interpretation.max-lawful-profile', ...extra });
const riichi = (prefix: 'riichi-ema-2025' | 'sanma-profile') => ({ configVersion: 1, yakuCatalogueId: `catalogue.yaku.${prefix}`, yakumanCatalogueId: `catalogue.yakuman.${prefix}`, decompositionPolicyId: `riichi-decomposition.${prefix === 'riichi-ema-2025' ? 'ema-2025-enumerate-max' : 'compatible-enumerate-max'}`, doraPolicyId: `dora.${prefix === 'riichi-ema-2025' ? 'riichi-ema-2025' : 'sanma-profile-with-nuki'}`, fuPolicyId: `fu.${prefix}`, limitTierPolicyId: `riichi-limit-tier.${prefix === 'riichi-ema-2025' ? 'ema-2025' : 'sanma-profile'}`, handValuePolicyId: `riichi-hand-value.${prefix === 'riichi-ema-2025' ? 'ema-2025' : 'sanma-profile'}` });

const fixtures: readonly Fixture[] = [
  { id: 'A01', family: { id: 'family.classical-western', allowedGrammars: ['classical-points-doubles'], handEvidenceCodecId: 'classical.hand.v1', roundOutcomeCodecId: 'classical.round.v1', strategyStateCodecId: 'classical.strategy.v1', allowedTileSetIds: ['tiles.flowers-144'], allowedSeatModelIds: ['seats.winds-4'] }, definition: root('mt-european-classical-paper', 'family.classical-western', 'classical-points-doubles', { playerCount: 4, seatModelId: 'seats.winds-4' }, { presetId: 'tiles.flowers-144', options: { bonusTilesEnabled: true } }, { presetId: 'shape.four-sets-pair', options: { irregularCatalogueId: 'catalogue.pattern.mt-european-classical-specials' } }, { handShapePolicyId: 'validation.classical-standard', policyIds: [] }, { configVersion: 1, presetId: 'classical.standard', profileBindingsId: 'classical.bindings.mt-european-classical' }, { policyIds: ['evidence-policy.classical-winning-context', 'evidence-policy.mt-european-classical-waits'], alwaysRequired: [] }, 'settlement.classical-pairwise', 'progression.rotate-every-hand', 'game-end.four-round-always-pass', source('mahjong-time.european-classical'), { eastMultiplier: 2, loserToLoser: true }), expectedCategories: { 'classical.standard': 'classical', 'classical.bindings.mt-european-classical': 'classical' } },
  { id: 'A02', family: { id: 'family.hong-kong', allowedGrammars: ['pattern-accumulator'], handEvidenceCodecId: 'hk.hand.v1', roundOutcomeCodecId: 'hk.round.v1', strategyStateCodecId: 'hk.strategy.v1', allowedTileSetIds: ['tiles.flowers-144'], allowedSeatModelIds: ['seats.winds-4'] }, definition: root('mt-hong-kong-paper', 'family.hong-kong', 'pattern-accumulator', { playerCount: 4, seatModelId: 'seats.winds-4' }, { presetId: 'tiles.flowers-144', options: { flowersSeasonsEnabled: true } }, { presetId: 'shape.four-sets-pair', options: { irregularCatalogueId: 'catalogue.pattern.hk-profile-specials' } }, { handShapePolicyId: 'validation.hk-profile', policyIds: [] }, accumulator('fan', 'catalogue.pattern.hk-profile', 'interaction.hk-profile', 'qualification.hk-profile', { conversionPolicyId: 'conversion.hk-fan-payment-table', capPolicyId: 'value-policy.hk-profile' }), { policyIds: ['evidence-policy.hk-profile'], alwaysRequired: ['evidence.winning-method', 'evidence.seat-wind', 'evidence.round-wind'] }, 'settlement.hk-profile', 'progression.hk-profile', 'game-end.hk-profile', source('mahjong-time.hong-kong')), expectedCategories: { 'catalogue.pattern.hk-profile': 'catalogue.pattern', 'qualification.hk-profile': 'qualification', 'conversion.hk-fan-payment-table': 'conversion' } },
  { id: 'A03', family: { id: 'family.mcr', allowedGrammars: ['pattern-accumulator'], handEvidenceCodecId: 'mcr.hand.v1', roundOutcomeCodecId: 'mcr.round.v1', strategyStateCodecId: 'mcr.strategy.v1', allowedTileSetIds: ['tiles.flowers-144'], allowedSeatModelIds: ['seats.winds-4'] }, definition: root('mcr-wmo-2006', 'family.mcr', 'pattern-accumulator', { playerCount: 4, seatModelId: 'seats.winds-4' }, { presetId: 'tiles.flowers-144', options: {} }, { presetId: 'shape.four-sets-pair', options: { irregularCatalogueId: 'catalogue.pattern.mcr-special-shapes' } }, { handShapePolicyId: 'validation.mcr-winning-shape', policyIds: ['validation.mcr-minimum-win-context'] }, accumulator('points', 'catalogue.pattern.mcr-wmo-2006', 'interaction.mcr-2006-non-combination', 'qualification.mcr-8-before-flowers', { postQualificationBonusPolicyId: 'post-qualification-bonus.mcr-flowers', conversionPolicyId: 'conversion.identity' }), { policyIds: ['evidence-policy.mcr-wmo-2006'], alwaysRequired: ['evidence.winning-method', 'evidence.winning-tile-provenance', 'evidence.seat-wind', 'evidence.round-wind'] }, 'settlement.mcr-2006', 'progression.always-pass', 'game-end.four-round-always-pass', source('mcr-ema-green-book-2006')), expectedCategories: { 'catalogue.pattern.mcr-wmo-2006': 'catalogue.pattern', 'post-qualification-bonus.mcr-flowers': 'post-qualification-bonus' } },
  { id: 'A04', family: { id: 'family.taiwanese-16-tile', allowedGrammars: ['pattern-accumulator'], handEvidenceCodecId: 'taiwan.hand.v1', roundOutcomeCodecId: 'taiwan.round.v1', strategyStateCodecId: 'taiwan.strategy.v1', allowedTileSetIds: ['tiles.flowers-144'], allowedSeatModelIds: ['seats.winds-4'] }, definition: root('mt-taiwanese-paper', 'family.taiwanese-16-tile', 'pattern-accumulator', { playerCount: 4, seatModelId: 'seats.winds-4' }, { presetId: 'tiles.flowers-144', options: { bonusTilesEnabled: true } }, { presetId: 'shape.five-sets-pair', options: { dealtConcealedTiles: 16, winningStructuralTiles: 17, irregularCatalogueId: 'catalogue.pattern.taiwanese-profile-specials' } }, { handShapePolicyId: 'validation.taiwanese-five-sets-pair', policyIds: [] }, accumulator('tai', 'catalogue.pattern.taiwanese-profile', 'interaction.taiwanese-profile', 'qualification.taiwanese-profile', { capPolicyId: 'value-policy.optional-table-cap', conversionPolicyId: 'conversion.identity' }), { policyIds: ['evidence-policy.taiwanese-profile'], alwaysRequired: ['evidence.winning-method', 'evidence.winning-tile-provenance'] }, 'settlement.taiwanese-winner-only', 'progression.taiwanese-profile', 'game-end.taiwanese-profile', source('mahjong-time.taiwanese')), expectedCategories: { 'shape.five-sets-pair': 'shape', 'catalogue.pattern.taiwanese-profile': 'catalogue.pattern' } },
  { id: 'A05', family: { id: 'family.riichi', allowedGrammars: ['riichi-han-fu'], handEvidenceCodecId: 'riichi.hand.v1', roundOutcomeCodecId: 'riichi.round.v1', strategyStateCodecId: 'riichi.strategy.v1', allowedTileSetIds: ['tiles.riichi-136'], allowedSeatModelIds: ['seats.riichi-winds-4'] }, definition: root('riichi-ema-2025', 'family.riichi', 'riichi-han-fu', { playerCount: 4, seatModelId: 'seats.riichi-winds-4' }, { presetId: 'tiles.riichi-136', options: { redFives: 0 } }, { presetId: 'shape.four-sets-pair', options: { irregularCatalogueId: 'catalogue.pattern.riichi-ema-2025-special-shapes' } }, { handShapePolicyId: 'validation.riichi-winning-shape', policyIds: ['validation.riichi-yaku-required'] }, riichi('riichi-ema-2025'), { policyIds: ['evidence-policy.riichi-ema-2025'], alwaysRequired: ['evidence.winning-method', 'evidence.winning-tile-provenance', 'evidence.seat-wind', 'evidence.round-wind'] }, 'settlement.riichi-ema-2025-four-player', 'progression.riichi-ema-2025-renchan', 'game-end.riichi-ema-2025', source('ema-riichi-2025')), expectedCategories: { 'catalogue.yaku.riichi-ema-2025': 'catalogue.yaku', 'dora.riichi-ema-2025': 'dora' } },
  { id: 'A06', family: { id: 'family.riichi-sanma', allowedGrammars: ['riichi-han-fu'], handEvidenceCodecId: 'sanma.hand.v1', roundOutcomeCodecId: 'sanma.round.v1', strategyStateCodecId: 'sanma.strategy.v1', allowedTileSetIds: ['tiles.sanma-108'], allowedSeatModelIds: ['seats.riichi-sanma-east-south-west'] }, definition: root('mt-sanma-paper', 'family.riichi-sanma', 'riichi-han-fu', { playerCount: 3, seatModelId: 'seats.riichi-sanma-east-south-west' }, { presetId: 'tiles.sanma-108', options: { redFives: 3, nukiDoraTile: 'north' } }, { presetId: 'shape.four-sets-pair', options: { irregularCatalogueId: 'catalogue.pattern.sanma-profile-special-shapes' } }, { handShapePolicyId: 'validation.riichi-winning-shape', policyIds: ['validation.sanma-no-chii', 'validation.riichi-yaku-required'] }, riichi('sanma-profile'), { policyIds: ['evidence-policy.riichi-sanma'], alwaysRequired: ['evidence.winning-method', 'evidence.winning-tile-provenance', 'evidence.seat-wind'] }, 'settlement.riichi-sanma', 'progression.riichi-sanma-renchan', 'game-end.riichi-sanma', source('mahjong-time.sanma')), expectedCategories: { 'tiles.sanma-108': 'tiles', 'validation.sanma-no-chii': 'validation', 'settlement.riichi-sanma': 'settlement' } },
  { id: 'A07', family: { id: 'family.zung-jung', allowedGrammars: ['pattern-accumulator'], handEvidenceCodecId: 'zung.hand.v1', roundOutcomeCodecId: 'zung.round.v1', strategyStateCodecId: 'zung.strategy.v1', allowedTileSetIds: ['tiles.standard-136'], allowedSeatModelIds: ['seats.winds-4'] }, definition: root('zung-jung-1.03-paper', 'family.zung-jung', 'pattern-accumulator', { playerCount: 4, seatModelId: 'seats.winds-4' }, { presetId: 'tiles.standard-136', options: {} }, { presetId: 'shape.four-sets-pair', options: { irregularCatalogueId: 'catalogue.pattern.zung-jung-special-shapes' } }, { handShapePolicyId: 'validation.zung-jung-winning-shape', policyIds: [] }, accumulator('points', 'catalogue.pattern.zung-jung-1.03-44', 'interaction.zung-jung-same-series-highest-only', 'qualification.none', { floorPolicyId: 'value-policy.zung-jung-zero-pattern-one', capPolicyId: 'value-policy.zung-jung-320-listed-limit', conversionPolicyId: 'conversion.identity' }), { policyIds: ['evidence-policy.zung-jung-1.03'], alwaysRequired: ['evidence.winning-method', 'evidence.winning-tile-provenance'] }, 'settlement.zung-jung-formal', 'progression.always-pass', 'game-end.zung-jung-profile', source('zung-jung-1.03')), expectedCategories: { 'catalogue.pattern.zung-jung-1.03-44': 'catalogue.pattern', 'value-policy.zung-jung-320-listed-limit': 'value-policy' } },
  { id: 'A08', family: { id: 'family.american-nmjl-style', allowedGrammars: ['target-catalogue'], handEvidenceCodecId: 'american.hand.v1', roundOutcomeCodecId: 'american.round.v1', strategyStateCodecId: 'american.strategy.v1', allowedTileSetIds: ['tiles.american-joker-capable'], allowedSeatModelIds: ['seats.american-four-player'] }, definition: root('american-nmjl-style-paper', 'family.american-nmjl-style', 'target-catalogue', { playerCount: 4, seatModelId: 'seats.american-four-player' }, { presetId: 'tiles.american-joker-capable', options: {} }, { presetId: 'shape.target-catalogue', options: {} }, { handShapePolicyId: 'validation.target-catalogue-match', policyIds: [] }, { configVersion: 1, catalogueRef: { id: 'catalogue.target.nmjl-2026-external-placeholder', version: '2026' }, matchPolicyId: 'target-match.nmjl-style', substitutionPolicyId: 'substitution.nmjl-style-joker', exposurePolicyId: 'target-exposure.nmjl-style', valuePolicyId: 'target-value.catalogue-defined' }, { policyIds: ['evidence-policy.american-nmjl-style'], alwaysRequired: [] }, 'settlement.american-profile', 'progression.american-profile', 'game-end.american-profile', source('nmjl-annual-card-ecosystem')), expectedCategories: { 'catalogue.target.nmjl-2026-external-placeholder': 'catalogue.target', 'substitution.nmjl-style-joker': 'substitution' } },
];

const exact = (keys: readonly string[]): JsonContract => ({ validate(value) { if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value as JsonObject).sort().join() !== [...keys].sort().join()) throw new Error('invalid'); return { value }; } });
const oneOf = (...contracts: readonly JsonContract[]): JsonContract => ({ validate(value) { for (const contract of contracts) try { return contract.validate(value); } catch { /* Try the next explicit shape. */ } throw new Error('invalid'); } });
const seatModels = new Map([['seats.winds-4', 4], ['seats.riichi-winds-4', 4], ['seats.riichi-sanma-east-south-west', 3], ['seats.american-four-player', 4]]);
const envFor = (fixture: Fixture): ResolverEnvironment => {
  const parameterised = new Map<string, string>([['tiles.flowers-144', 'tiles.flowers-options'], ['tiles.riichi-136', 'riichi-tiles-options'], ['tiles.sanma-108', 'sanma-tiles-options'], ['shape.four-sets-pair', 'four-set-options'], ['shape.five-sets-pair', 'five-set-options'], ['settlement.classical-pairwise', 'classical-settlement-options']]);
  const registry = new RegistryBank(architectureSeedEntries.map(entry => parameterised.has(entry.id) ? { ...entry, parameterSchemaId: parameterised.get(entry.id) } : entry));
  const contracts = new Map<string, JsonContract>([
    ['tiles.flowers-options', oneOf(exact(['bonusTilesEnabled']), exact(['flowersSeasonsEnabled']))], ['riichi-tiles-options', exact(['redFives'])], ['sanma-tiles-options', exact(['nukiDoraTile', 'redFives'])], ['four-set-options', exact(['irregularCatalogueId'])], ['five-set-options', exact(['dealtConcealedTiles', 'irregularCatalogueId', 'winningStructuralTiles'])], ['classical-settlement-options', exact(['eastMultiplier', 'loserToLoser'])],
  ]);
  const profiles = new Map([[`${fixture.definition.identity.id}@${fixture.definition.identity.version}`, fixture.definition as ProfileAuthoringDefinition]]);
  return { registry, families: { get: id => id === fixture.family.id ? fixture.family : undefined }, seatModels: { get: id => { const playerCount = seatModels.get(id); return playerCount ? { id, playerCount } : undefined; } }, profiles: { get: ref => profiles.get(`${ref.id}@${ref.version}`) }, contracts: { get: id => contracts.get(id) }, familyContracts: { get: id => id === 'family.classical-western' ? { validate: value => { const result = exact(['configVersion', 'presetId', 'profileBindingsId']).validate(value); return { ...result, references: [{ path: 'presetId', category: 'classical' as const, id: 'classical.standard' }, { path: 'profileBindingsId', category: 'classical' as const, id: 'classical.bindings.mt-european-classical' }] }; } } : undefined }, targetCatalogues: { has: ref => ref.id === 'catalogue.target.nmjl-2026-external-placeholder' && ref.version === '2026' } };
};

describe('eight architecture fixtures', () => {
  it.each(fixtures)('$id is structurally representable and deliberately non-playable', async fixture => {
    const inspection = inspectProfile(fixture.definition, envFor(fixture));
    expect(inspection.profile?.identity.grammar).toBe(fixture.family.allowedGrammars[0]);
    for (const [id, category] of Object.entries(fixture.expectedCategories)) expect(inspection.references).toContainEqual(expect.objectContaining({ id, expectedCategory: category }));
    expect(inspection.references.filter(reference => reference.role === 'metadata')).toEqual([expect.objectContaining({ id: (fixture.definition.definition.provenance as { sources: string[] }).sources[0], actualStatus: 'metadata' })]);
    expect(inspection.references.filter(reference => reference.role === 'functional').every(reference => reference.actualStatus === 'architecture-only' && reference.blockerCode === 'REFERENCE_NOT_EXECUTABLE'), JSON.stringify(inspection.references)).toBe(true);
    await expect(resolvePlayableProfile({ id: fixture.definition.identity.id, version: fixture.definition.identity.version }, envFor(fixture))).rejects.toThrow('PROFILE_NOT_PLAYABLE:REFERENCE_NOT_EXECUTABLE');
  });

  it('keeps family codecs distinct and seat cardinality explicit', () => {
    expect(new Set(fixtures.map(fixture => fixture.family.handEvidenceCodecId)).size).toBe(8);
    for (const fixture of fixtures) expect(() => assertFamilyCompatibility(fixture.family, fixture.family.allowedGrammars[0], fixture.family, (fixture.definition.definition.tileSet as { presetId: string }).presetId, (fixture.definition.definition.table as { seatModelId: string }).seatModelId)).not.toThrow();
    const mismatch = JSON.parse(JSON.stringify(fixtures[0].definition)) as RootProfileDefinition;
    (mismatch.definition.table as { playerCount: number }).playerCount = 3;
    expect(inspectProfile(mismatch, envFor(fixtures[0])).blockers).toEqual(expect.arrayContaining([expect.objectContaining({ blockerCode: 'SEAT_PLAYER_COUNT_MISMATCH' })]));
  });
});
