import { describe, expect, it } from 'vitest';
import { detectMcr2006Fans, MCR_2006_FAN_BINDINGS, MCR_2006_EVIDENCE_POLICY_ID, MCR_2006_INPUT_EVIDENCE } from './mcr-detectors';
import type { McrScoringInput } from './mcr-scoring-input';

const t=(s:'characters'|'bamboo'|'dots',rank:number)=>({face:{family:'suit' as const,suit:s,rank}});
const w=(wind:'east'|'south'|'west'|'north')=>({face:{family:'wind' as const,wind}});
const d=(dragon:'red'|'green'|'white')=>({face:{family:'dragon' as const,dragon}});
const base=():McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:[t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',7),t('characters',7),t('characters',7),t('dots',5),t('dots',5)],winningTile:t('dots',5),flowerCount:0},context:{winSource:'self-draw',resolvedWinEvent:'none',lastVisibleCopy:false}});
const ids=(input:McrScoringInput)=>detectMcr2006Fans(input).candidates.map(x=>x.bindingId);

describe('MCR 2006 detector catalogue',()=>{
 const proves=(input:McrScoringInput, slug:string, value:number)=>{const b=`mcr2006.fan.${slug}`;const found=detectMcr2006Fans(input).candidates.filter(x=>x.bindingId===b);expect(found).toHaveLength(1);expect(found.every(x=>x.value===value&&x.sourceLocator?.includes('§3.8.1'))).toBe(true);expect(MCR_2006_FAN_BINDINGS.find(x=>x.id===b)?.stage).toBe('candidate'); const occurrence=found[0]!; expect(occurrence.id).toContain(`${b}#${occurrence.interpretationId}#`); if(['big-four-winds','big-three-dragons','little-four-winds','little-three-dragons'].includes(slug))expect(occurrence.interpretationId).toMatch(/^ordinary:/); else expect(occurrence.interpretationId).toBe('hand'); return detectMcr2006Fans(input);};
 it('proves source predicates 1–10 through actual detector routes',()=>{
  const ordinary=(tiles:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:tiles,winningTile:tiles.at(-1)!,flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}});
  proves(ordinary([w('east'),w('east'),w('east'),w('south'),w('south'),w('south'),w('west'),w('west'),w('west'),w('north'),w('north'),w('north'),d('red'),d('red')]),'big-four-winds',88);
  proves(ordinary([d('red'),d('red'),d('red'),d('green'),d('green'),d('green'),d('white'),d('white'),d('white'),t('characters',1),t('characters',2),t('characters',3),t('characters',5),t('characters',5)]),'big-three-dragons',88);
  proves(ordinary([t('bamboo',2),t('bamboo',3),t('bamboo',4),t('bamboo',2),t('bamboo',2),t('bamboo',2),t('bamboo',6),t('bamboo',6),t('bamboo',6),t('bamboo',8),t('bamboo',8),t('bamboo',8),d('green'),d('green')]),'all-green',88);
  proves(ordinary([t('characters',1),t('characters',1),t('characters',1),t('characters',2),t('characters',3),t('characters',4),t('characters',5),t('characters',6),t('characters',7),t('characters',8),t('characters',9),t('characters',9),t('characters',9),t('characters',5)]),'nine-gates',88);
  const four=ordinary([t('characters',5),t('characters',5)]);four.evidence.fixedGroups=[{kind:'kong',exposure:'melded',tiles:[t('characters',1),t('characters',1),t('characters',1),t('characters',1)]},{kind:'kong',exposure:'concealed',tiles:[t('dots',2),t('dots',2),t('dots',2),t('dots',2)]},{kind:'kong',exposure:'melded',tiles:[t('bamboo',3),t('bamboo',3),t('bamboo',3),t('bamboo',3)]},{kind:'kong',exposure:'concealed',tiles:[w('east'),w('east'),w('east'),w('east')]}];proves(four,'four-kongs',88);
  proves(ordinary([t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',4),t('characters',4),t('characters',5),t('characters',5),t('characters',6),t('characters',6),t('characters',7),t('characters',7)]),'seven-shifted-pairs',88);
  proves(ordinary([t('characters',1),t('characters',9),t('bamboo',1),t('bamboo',9),t('dots',1),t('dots',9),w('east'),w('south'),w('west'),w('north'),d('red'),d('green'),d('white'),t('characters',1)]),'thirteen-orphans',88);
  proves(ordinary([t('characters',1),t('characters',1),t('characters',1),t('characters',9),t('characters',9),t('characters',9),t('bamboo',1),t('bamboo',1),t('bamboo',1),t('bamboo',9),t('bamboo',9),t('bamboo',9),t('dots',1),t('dots',1)]),'all-terminals',64);
  proves(ordinary([w('east'),w('east'),w('east'),w('south'),w('south'),w('south'),w('west'),w('west'),w('west'),t('characters',1),t('characters',2),t('characters',3),w('north'),w('north')]),'little-four-winds',64);
  proves(ordinary([d('red'),d('red'),d('red'),d('green'),d('green'),d('green'),t('characters',1),t('characters',2),t('characters',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),d('white'),d('white')]),'little-three-dragons',64);
 });
 it('proves Seven Pairs and Thirteen Orphans through their required irregular routes',()=>{
  const seven=base(); seven.evidence.freeTiles=[t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',4),t('characters',4),t('characters',5),t('characters',5),t('characters',6),t('characters',6),t('characters',7),t('characters',7)];seven.evidence.winningTile=t('characters',7); const a=detectMcr2006Fans(seven); expect(a.interpretations.some(x=>x.kind==='seven-pairs')).toBe(true);expect(a.candidates.filter(x=>x.bindingId==='mcr2006.fan.seven-shifted-pairs')).toHaveLength(1);
  const orphan=base(); orphan.evidence.freeTiles=[t('characters',1),t('characters',9),t('bamboo',1),t('bamboo',9),t('dots',1),t('dots',9),w('east'),w('south'),w('west'),w('north'),d('red'),d('green'),d('white'),t('characters',1)];orphan.evidence.winningTile=t('characters',1);const b=detectMcr2006Fans(orphan);expect(b.interpretations.some(x=>x.kind==='thirteen-orphans')).toBe(true);expect(b.interpretations.some(x=>x.kind==='ordinary')).toBe(false);expect(b.candidates.filter(x=>x.bindingId==='mcr2006.fan.thirteen-orphans')).toHaveLength(1);
 });
 it('keeps Three Kongs interpretation-owned and Greater Knitted assignment-owned',()=>{
  const k=base();k.evidence.fixedGroups=[{kind:'kong',exposure:'melded',tiles:[t('characters',1),t('characters',1),t('characters',1),t('characters',1)]},{kind:'kong',exposure:'concealed',tiles:[t('dots',2),t('dots',2),t('dots',2),t('dots',2)]},{kind:'kong',exposure:'melded',tiles:[t('bamboo',3),t('bamboo',3),t('bamboo',3),t('bamboo',3)]}];k.evidence.freeTiles=[t('characters',4),t('characters',5),t('characters',6),t('dots',7),t('dots',7)];k.evidence.winningTile=t('dots',7);const kr=detectMcr2006Fans(k).candidates.filter(x=>x.bindingId==='mcr2006.fan.three-kongs');expect(kr).toHaveLength(1);expect(kr[0]!.interpretationId).toMatch(/^ordinary:/);
  const g=base();g.evidence.freeTiles=[w('east'),w('south'),w('west'),w('north'),d('red'),d('green'),d('white'),t('characters',1),t('characters',4),t('characters',7),t('bamboo',2),t('bamboo',5),t('dots',3),t('dots',6)];g.evidence.winningTile=t('dots',6);const gr=detectMcr2006Fans(g);expect(gr.interpretations.some(x=>x.kind==='greater-knitted')).toBe(true);const gc=gr.candidates.filter(x=>x.bindingId==='mcr2006.fan.greater-honors-knitted');expect(gc).toHaveLength(1);expect(gc[0]!.interpretationId).toMatch(/^greater-knitted:/);
 });
 it('proves rows 11–20 values, routes, and deterministic occurrences',()=>{
  const mk=(tiles:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:tiles,winningTile:tiles.at(-1)!,flowerCount:0},context:{winSource:'discard' as const,resolvedWinEvent:'none' as const,lastVisibleCopy:false}});
  const check=(input:McrScoringInput,slug:string,value:number,route:'hand'|'ordinary'|'seven-pairs'|'greater-knitted')=>{const b=`mcr2006.fan.${slug}`,r=detectMcr2006Fans(input),cs=r.candidates.filter(x=>x.bindingId===b);expect(cs).toHaveLength(1);expect(cs[0]!.value).toBe(value);expect(cs[0]!.sourceLocator).toContain('§3.8.1');expect(MCR_2006_FAN_BINDINGS.find(x=>x.id===b)?.stage).toBe('candidate');expect(cs[0]!.id).toContain(`${b}#${cs[0]!.interpretationId}#`);if(route==='hand')expect(cs[0]!.interpretationId).toBe('hand');else expect(cs[0]!.interpretationId).toMatch(new RegExp(`^${route}:`));return r;};
  check(mk([w('east'),w('east'),w('east'),w('south'),w('south'),w('south'),w('west'),w('west'),w('west'),d('red'),d('red'),d('red'),d('green'),d('green')]),'all-honors',64,'hand');
  check(mk([t('characters',2),t('characters',2),t('characters',2),t('dots',3),t('dots',3),t('dots',3),t('bamboo',4),t('bamboo',4),t('bamboo',4),w('east'),w('east'),w('east'),t('characters',5),t('characters',5)]),'four-concealed-pungs',64,'ordinary');
  const melded=mk([t('dots',3),t('dots',3),t('dots',3),t('bamboo',4),t('bamboo',4),t('bamboo',4),w('east'),w('east'),w('east'),t('characters',5),t('characters',5)]);melded.evidence.fixedGroups=[{kind:'pung',exposure:'melded',tiles:[t('characters',2),t('characters',2),t('characters',2)]}];expect(detectMcr2006Fans(melded).candidates.some(x=>x.bindingId==='mcr2006.fan.four-concealed-pungs')).toBe(false);
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('characters',7),t('characters',8),t('characters',9),t('characters',7),t('characters',8),t('characters',9),t('characters',5),t('characters',5)]),'pure-terminal-chows',64,'ordinary');
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('dots',5),t('dots',5)]),'quadruple-chow',48,'ordinary');
  check(mk([t('characters',1),t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',3),t('characters',4),t('characters',4),t('characters',4),t('dots',5),t('dots',5)]),'four-pure-shifted-pungs',48,'ordinary');
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('characters',2),t('characters',3),t('characters',4),t('characters',3),t('characters',4),t('characters',5),t('characters',4),t('characters',5),t('characters',6),t('dots',5),t('dots',5)]),'four-pure-shifted-chows',32,'ordinary');
  const kong=mk([t('bamboo',4),t('bamboo',5),t('bamboo',6),t('characters',5),t('characters',5)]);kong.evidence.fixedGroups=[{kind:'kong',exposure:'melded',tiles:[t('characters',1),t('characters',1),t('characters',1),t('characters',1)]},{kind:'kong',exposure:'concealed',tiles:[t('dots',2),t('dots',2),t('dots',2),t('dots',2)]},{kind:'kong',exposure:'melded',tiles:[t('bamboo',3),t('bamboo',3),t('bamboo',3),t('bamboo',3)]}];check(kong,'three-kongs',32,'ordinary');
  check(mk([t('characters',1),t('characters',1),t('characters',1),t('characters',9),t('characters',9),t('characters',9),w('east'),w('east'),w('east'),d('red'),d('red'),d('red'),t('bamboo',9),t('bamboo',9)]),'all-terminals-and-honors',32,'hand');
  const seven=check(mk([t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('dots',3),t('dots',3),t('dots',4),t('dots',4),t('bamboo',5),t('bamboo',5),t('bamboo',6),t('bamboo',6),w('east'),w('east')]),'seven-pairs',24,'hand');expect(seven.interpretations.some(x=>x.kind==='seven-pairs')).toBe(true);
  const greater=check(mk([w('east'),w('south'),w('west'),w('north'),d('red'),d('green'),d('white'),t('characters',1),t('characters',4),t('characters',7),t('bamboo',2),t('bamboo',5),t('dots',3),t('dots',6)]),'greater-honors-knitted',24,'greater-knitted');expect(greater.interpretations.some(x=>x.kind==='greater-knitted')).toBe(true);
 });
 it('proves rows 21–30 and preserves source-owned subset occurrences',()=>{
  const mk=(x:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:x,winningTile:x.at(-1)!,flowerCount:0},context:{winSource:'discard' as const,resolvedWinEvent:'none' as const,lastVisibleCopy:false}});
  const check=(i:McrScoringInput,s:string,v:number,kind:'hand'|'ordinary',n=1)=>{const b=`mcr2006.fan.${s}`,cs=detectMcr2006Fans(i).candidates.filter(x=>x.bindingId===b);expect(cs).toHaveLength(n);expect(cs.every(x=>x.value===v&&x.sourceLocator?.includes('§3.8.1')&&MCR_2006_FAN_BINDINGS.find(y=>y.id===b)?.stage==='candidate'&&x.id.includes(`${b}#${x.interpretationId}#`))).toBe(true);if(kind==='hand')expect(cs.every(x=>x.interpretationId==='hand')).toBe(true);else expect(cs.every(x=>x.interpretationId.startsWith('ordinary:'))).toBe(true);};
  check(mk([t('characters',2),t('characters',2),t('characters',2),t('dots',4),t('dots',4),t('dots',4),t('bamboo',6),t('bamboo',6),t('bamboo',6),t('characters',8),t('characters',8),t('characters',8),t('dots',2),t('dots',2)]),'all-even-pungs',24,'ordinary');
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('characters',4),t('characters',5),t('characters',6),t('characters',7),t('characters',8),t('characters',9),t('characters',7),t('characters',7),t('characters',7),t('characters',5),t('characters',5)]),'full-flush',24,'hand');
  const quad=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('dots',5),t('dots',5)]);check(quad,'pure-triple-chow',24,'ordinary',4);
  const pungs=mk([t('characters',1),t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',3),t('characters',4),t('characters',4),t('characters',4),t('dots',5),t('dots',5)]);check(pungs,'pure-shifted-pungs',24,'ordinary',2);
  check(mk([t('characters',7),t('characters',8),t('characters',9),t('dots',7),t('dots',8),t('dots',9),t('bamboo',7),t('bamboo',7),t('bamboo',7),t('characters',8),t('characters',8),t('characters',8),t('dots',9),t('dots',9)]),'upper-tiles',24,'hand');
  check(mk([t('characters',4),t('characters',5),t('characters',6),t('dots',4),t('dots',5),t('dots',6),t('bamboo',4),t('bamboo',4),t('bamboo',4),t('characters',5),t('characters',5),t('characters',5),t('dots',6),t('dots',6)]),'middle-tiles',24,'hand');
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('dots',1),t('dots',2),t('dots',3),t('bamboo',1),t('bamboo',1),t('bamboo',1),t('characters',2),t('characters',2),t('characters',2),t('dots',3),t('dots',3)]),'lower-tiles',24,'hand');
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('characters',4),t('characters',5),t('characters',6),t('characters',7),t('characters',8),t('characters',9),t('bamboo',2),t('bamboo',2),t('bamboo',2),t('dots',5),t('dots',5)]),'pure-straight',16,'ordinary');
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('characters',7),t('characters',8),t('characters',9),t('dots',1),t('dots',2),t('dots',3),t('dots',7),t('dots',8),t('dots',9),t('bamboo',5),t('bamboo',5)]),'three-suited-terminal-chows',16,'ordinary');
  const chows=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',2),t('characters',3),t('characters',4),t('characters',3),t('characters',4),t('characters',5),t('characters',4),t('characters',5),t('characters',6),t('dots',5),t('dots',5)]);check(chows,'pure-shifted-chows',16,'ordinary',2);
  const step2=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',3),t('characters',4),t('characters',5),t('characters',5),t('characters',6),t('characters',7),t('bamboo',7),t('bamboo',7),t('bamboo',7),t('dots',5),t('dots',5)]);check(step2,'pure-shifted-chows',16,'ordinary');
  const mixed=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',2),t('characters',3),t('characters',4),t('characters',5),t('characters',6),t('characters',7),t('bamboo',7),t('bamboo',7),t('bamboo',7),t('dots',5),t('dots',5)]);expect(detectMcr2006Fans(mixed).candidates.some(x=>x.bindingId==='mcr2006.fan.pure-shifted-chows')).toBe(false);
 });
 it('proves rows 31–40 including knitted and mixed-straight identities',()=>{
  const mk=(x:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:x,winningTile:x.at(-1)!,flowerCount:0},context:{winSource:'discard' as const,resolvedWinEvent:'none' as const,lastVisibleCopy:false}});
  const check=(i:McrScoringInput,s:string,v:number,route:string,n=1)=>{const b=`mcr2006.fan.${s}`,cs=detectMcr2006Fans(i).candidates.filter(x=>x.bindingId===b);expect(cs).toHaveLength(n);expect(cs.every(x=>x.value===v&&x.sourceLocator?.includes('§3.8.1')&&x.id.includes(`${b}#${x.interpretationId}#`))).toBe(true);expect(cs.every(x=>x.interpretationId.startsWith(route))).toBe(true);};
  check(mk([t('characters',3),t('characters',4),t('characters',5),t('dots',4),t('dots',5),t('dots',6),t('bamboo',5),t('bamboo',6),t('bamboo',7),t('characters',5),t('characters',5),t('characters',5),t('dots',5),t('dots',5)]),'all-fives',16,'ordinary:');
  check(mk([t('characters',5),t('characters',5),t('characters',5),t('dots',5),t('dots',5),t('dots',5),t('bamboo',5),t('bamboo',5),t('bamboo',5),t('characters',1),t('characters',2),t('characters',3),t('dots',7),t('dots',7)]),'triple-pung',16,'ordinary:');
  const concealed=mk([t('characters',2),t('characters',2),t('characters',2),t('dots',3),t('dots',3),t('dots',3),t('bamboo',4),t('bamboo',4),t('bamboo',4),t('dots',5),t('dots',5)]);concealed.evidence.fixedGroups=[{kind:'chow',exposure:'melded',tiles:[t('characters',6),t('characters',7),t('characters',8)]}];check(concealed,'three-concealed-pungs',16,'ordinary:');
  const lesser=mk([w('east'),w('south'),w('west'),d('red'),d('green'),t('characters',1),t('characters',4),t('characters',7),t('bamboo',2),t('bamboo',5),t('bamboo',8),t('dots',3),t('dots',6),t('dots',9)]);check(lesser,'lesser-honors-knitted',12,'lesser-knitted:');
  const knit=mk([t('characters',1),t('characters',4),t('characters',7),t('bamboo',2),t('bamboo',5),t('bamboo',8),t('dots',3),t('dots',6),t('dots',9),w('east'),w('east'),w('east'),d('red'),d('red')]);check(knit,'knitted-straight',12,'knitted-straight:');
  check(mk([t('characters',6),t('characters',7),t('characters',8),t('dots',7),t('dots',8),t('dots',9),t('bamboo',6),t('bamboo',6),t('bamboo',6),t('characters',9),t('characters',9),t('characters',9),t('dots',8),t('dots',8)]),'upper-four',12,'hand');check(mk([t('characters',1),t('characters',2),t('characters',3),t('dots',2),t('dots',3),t('dots',4),t('bamboo',1),t('bamboo',1),t('bamboo',1),t('characters',4),t('characters',4),t('characters',4),t('dots',2),t('dots',2)]),'lower-four',12,'hand');
  check(mk([w('east'),w('east'),w('east'),w('south'),w('south'),w('south'),w('west'),w('west'),w('west'),t('characters',1),t('characters',2),t('characters',3),t('dots',5),t('dots',5)]),'big-three-winds',12,'ordinary:');
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',7),t('characters',7),t('characters',7),t('dots',5),t('dots',5)]),'mixed-straight',8,'ordinary:');
  const reversible=mk([t('dots',1),t('dots',2),t('dots',3),t('dots',3),t('dots',4),t('dots',5),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('bamboo',8),t('bamboo',8),t('bamboo',8),d('white'),d('white')]);check(reversible,'reversible-tiles',8,'hand');
 });
 it('subtracts one knitted assignment copy and accepts either lawful five-tile remainder',()=>{
  const mk=(x:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:x,winningTile:x.at(-1)!,flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}}); const assignment=[t('characters',1),t('characters',4),t('characters',7),t('bamboo',2),t('bamboo',5),t('bamboo',8),t('dots',3),t('dots',6),t('dots',9)]; const chow=mk([...assignment,t('characters',2),t('characters',3),t('characters',4),d('red'),d('red')]);const r=detectMcr2006Fans(chow),cs=r.candidates.filter(x=>x.bindingId==='mcr2006.fan.knitted-straight');expect(r.interpretations.some(x=>x.kind==='knitted-straight')).toBe(true);expect(cs).toHaveLength(1);expect(cs[0]!.value).toBe(12);expect(cs[0]!.sourceLocator).toContain('§3.8.1');expect(cs[0]!.id).toContain('assignment:'); const bad=mk([...assignment,t('characters',2),t('characters',2),t('characters',3),d('red'),d('green')]);expect(detectMcr2006Fans(bad).interpretations.some(x=>x.kind==='knitted-straight')).toBe(false);
  const lesser=mk([w('east'),w('south'),w('west'),d('red'),d('green'),t('characters',1),t('characters',4),t('characters',7),t('bamboo',2),t('bamboo',5),t('bamboo',8),t('dots',3),t('dots',6),t('dots',9)]);const lr=detectMcr2006Fans(lesser);expect(lr.interpretations.some(x=>x.kind==='lesser-knitted')).toBe(true);expect(lr.candidates.some(x=>x.bindingId==='mcr2006.fan.lesser-honors-knitted')).toBe(true);expect(lr.interpretations.some(x=>x.kind==='knitted-straight')).toBe(false);expect(lr.candidates.some(x=>x.bindingId==='mcr2006.fan.knitted-straight')).toBe(false);
 });
 it('proves rows 41–50, event conjunctions, and Kong pair occurrences',()=>{
  const mk=(x:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:x,winningTile:x.at(-1)!,flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}});const check=(i:McrScoringInput,s:string,v:number,n=1)=>{const b=`mcr2006.fan.${s}`,cs=detectMcr2006Fans(i).candidates.filter(x=>x.bindingId===b);expect(cs).toHaveLength(n);expect(cs.every(x=>x.value===v&&x.sourceLocator?.includes('§3.8.1')&&x.id.includes(`${b}#${x.interpretationId}#`))).toBe(true);};
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('dots',1),t('dots',2),t('dots',3),t('bamboo',1),t('bamboo',2),t('bamboo',3),t('characters',7),t('characters',7),t('characters',7),t('dots',5),t('dots',5)]),'mixed-triple-chow',8);check(mk([t('characters',1),t('characters',1),t('characters',1),t('dots',2),t('dots',2),t('dots',2),t('bamboo',3),t('bamboo',3),t('bamboo',3),t('characters',4),t('characters',5),t('characters',6),t('dots',5),t('dots',5)]),'mixed-shifted-pungs',8);
  const chicken=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',6),t('characters',7),t('characters',8),w('east'),w('east')]);const cr=detectMcr2006Fans(chicken);expect(cr.interpretations.length).toBeGreaterThan(0);expect(MCR_2006_FAN_BINDINGS.find(x=>x.id==='mcr2006.fan.chicken-hand')).toMatchObject({value:8,stage:'fallback'});expect(cr.candidates.some(x=>x.bindingId==='mcr2006.fan.chicken-hand')).toBe(false);
  for(const [event,source,slug] of [['last-wall-draw','self-draw','last-tile-draw'],['last-discard','discard','last-tile-claim'],['kong-replacement','self-draw','out-with-replacement-tile'],['rob-kong','discard','robbing-the-kong']] as const){const x=base();x.context.winSource=source;x.context.resolvedWinEvent=event;check(x,slug,8);}
  const kong=mk([t('bamboo',3),t('bamboo',4),t('bamboo',5),w('east'),w('east'),w('east'),t('characters',5),t('characters',5)]);kong.evidence.fixedGroups=[{kind:'kong',exposure:'concealed',tiles:[t('characters',1),t('characters',1),t('characters',1),t('characters',1)]},{kind:'kong',exposure:'concealed',tiles:[t('dots',2),t('dots',2),t('dots',2),t('dots',2)]}];check(kong,'two-concealed-kongs',8);
  check(mk([t('characters',1),t('characters',1),t('characters',1),t('dots',2),t('dots',2),t('dots',2),t('bamboo',3),t('bamboo',3),t('bamboo',3),w('east'),w('east'),w('east'),t('characters',5),t('characters',5)]),'all-pungs',6);check(mk([t('characters',1),t('characters',2),t('characters',3),t('characters',4),t('characters',5),t('characters',6),t('characters',7),t('characters',8),t('characters',9),w('east'),w('east'),w('east'),t('characters',5),t('characters',5)]),'half-flush',6);
 });
 it('keeps rows 41–50 repeated occurrences and wrong-source events explicit',()=>{
  const mk=(x:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:x,winningTile:x.at(-1)!,flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}});const idsFor=(i:McrScoringInput,s:string)=>detectMcr2006Fans(i).candidates.filter(x=>x.bindingId===`mcr2006.fan.${s}`);
  const chows=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('dots',1),t('dots',2),t('dots',3),t('bamboo',1),t('bamboo',2),t('bamboo',3),t('dots',5),t('dots',5)]);const a=idsFor(chows,'mixed-triple-chow');expect(a).toHaveLength(2);expect(new Set(a.map(x=>x.id)).size).toBe(2);expect(new Set(a.map(x=>x.interpretationId)).size).toBe(1);
  const pungs=mk([t('characters',1),t('characters',1),t('characters',1),t('characters',4),t('characters',4),t('characters',4),t('dots',2),t('dots',2),t('dots',2),t('bamboo',3),t('bamboo',3),t('bamboo',3),t('dots',5),t('dots',5)]);const b=idsFor(pungs,'mixed-shifted-pungs');expect(b).toHaveLength(2);expect(new Set(b.map(x=>x.id)).size).toBe(2);expect(new Set(b.map(x=>x.interpretationId)).size).toBe(1);
  const k=mk([t('characters',4),t('characters',5),t('characters',6),t('dots',5),t('dots',5)]);k.evidence.fixedGroups=[{kind:'kong',exposure:'concealed',tiles:[t('characters',1),t('characters',1),t('characters',1),t('characters',1)]},{kind:'kong',exposure:'concealed',tiles:[t('dots',2),t('dots',2),t('dots',2),t('dots',2)]},{kind:'kong',exposure:'concealed',tiles:[t('bamboo',3),t('bamboo',3),t('bamboo',3),t('bamboo',3)]}];const c=idsFor(k,'two-concealed-kongs');expect(c).toHaveLength(3);expect(new Set(c.map(x=>x.id)).size).toBe(3);
  for(const [event,source,slug] of [['last-wall-draw','discard','last-tile-draw'],['last-discard','self-draw','last-tile-claim'],['kong-replacement','discard','out-with-replacement-tile'],['rob-kong','self-draw','robbing-the-kong']] as const){const x=base();x.context.resolvedWinEvent=event;x.context.winSource=source;expect(detectMcr2006Fans(x).candidates.some(y=>y.bindingId===`mcr2006.fan.${slug}`)).toBe(false);}
  for(const s of ['mixed-triple-chow','mixed-shifted-pungs','last-tile-draw','last-tile-claim','out-with-replacement-tile','robbing-the-kong','two-concealed-kongs','all-pungs','half-flush'])expect(MCR_2006_FAN_BINDINGS.find(x=>x.id===`mcr2006.fan.${s}`)?.stage).toBe('candidate');
 });
 it('proves rows 51–60 source routes and hand ownership',()=>{
  const mk=(x:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:x,winningTile:x.at(-1)!,flowerCount:0},context:{winSource:'self-draw',resolvedWinEvent:'none',lastVisibleCopy:false}});const check=(i:McrScoringInput,s:string,v:number,n=1)=>{const b=`mcr2006.fan.${s}`,cs=detectMcr2006Fans(i).candidates.filter(x=>x.bindingId===b);expect(cs).toHaveLength(n);expect(cs.every(x=>x.value===v&&x.sourceLocator?.includes('§3.8.1'))).toBe(true);};
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('dots',2),t('dots',3),t('dots',4),t('bamboo',3),t('bamboo',4),t('bamboo',5),t('characters',7),t('characters',7),t('characters',7),t('dots',5),t('dots',5)]),'mixed-shifted-chows',6);
  check(mk([t('characters',1),t('characters',2),t('characters',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('dots',7),t('dots',8),t('dots',9),w('east'),w('east'),w('east'),d('red'),d('red')]),'all-types',6);
  const full=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',7),t('characters',7),t('characters',7),t('dots',5),t('dots',5)]);check(full,'fully-concealed-hand',4);expect(detectMcr2006Fans(full).candidates.filter(x=>x.bindingId==='mcr2006.fan.fully-concealed-hand')[0]!.interpretationId).toBe('hand');
  const dragon=mk([d('red'),d('red'),d('red'),d('green'),d('green'),d('green'),t('characters',1),t('characters',2),t('characters',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('dots',5),t('dots',5)]);check(dragon,'two-dragon-pungs',6);check(dragon,'dragon-pung',2,2);
  const outside=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',7),t('dots',8),t('dots',9),w('east'),w('east'),w('east'),t('bamboo',9),t('bamboo',9),t('bamboo',9),d('red'),d('red')]);check(outside,'outside-hand',4);
  const last=base();last.context.lastVisibleCopy=true;check(last,'last-tile',4);const wind=mk([w('east'),w('east'),w('east'),t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',5),t('characters',5)]);wind.context.prevailingWind='east';check(wind,'prevalent-wind',2);
 });
 it('closes rows 51–60 occurrence and evidence boundaries',()=>{
  const melded:McrScoringInput={evidence:{fixedGroups:[{kind:'chow',exposure:'melded',tiles:[t('characters',1),t('characters',2),t('characters',3)]},{kind:'chow',exposure:'melded',tiles:[t('dots',4),t('dots',5),t('dots',6)]},{kind:'chow',exposure:'melded',tiles:[t('bamboo',7),t('bamboo',8),t('bamboo',9)]},{kind:'pung',exposure:'melded',tiles:[w('east'),w('east'),w('east')]}],freeTiles:[d('red'),d('red')],winningTile:d('red'),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}};const r=detectMcr2006Fans(melded),m=r.candidates.filter(x=>x.bindingId==='mcr2006.fan.melded-hand');expect(r.interpretations.some(x=>x.kind==='ordinary')).toBe(true);expect(m).toHaveLength(1);expect(m[0]).toMatchObject({value:6});expect(m[0]!.interpretationId).toMatch(/^ordinary:/);const self={...melded,context:{...melded.context,winSource:'self-draw' as const}};expect(detectMcr2006Fans(self).candidates.some(x=>x.bindingId==='mcr2006.fan.melded-hand')).toBe(false);
  const x=base();x.context.lastVisibleCopy=true;const last=detectMcr2006Fans(x).candidates.filter(y=>y.bindingId==='mcr2006.fan.last-tile');expect(last).toHaveLength(1);expect(last[0]).toMatchObject({value:4,interpretationId:'context'});const unknown=base();delete unknown.context.lastVisibleCopy;expect(detectMcr2006Fans(unknown).missingEvidenceIds).toContain('evidence.last-visible-copy');
  const wind=base();wind.evidence.freeTiles=[w('east'),w('east'),w('east'),t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',5),t('characters',5)];wind.evidence.winningTile=t('characters',5);wind.context.prevailingWind='south';expect(detectMcr2006Fans(wind).candidates.some(y=>y.bindingId==='mcr2006.fan.prevalent-wind')).toBe(false);delete wind.context.prevailingWind;expect(detectMcr2006Fans(wind).missingEvidenceIds).toContain('evidence.round-wind');
 });
 it('completes the remaining 51–60 source bridge assertions',()=>{
  const mk=(x:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:x,winningTile:x.at(-1)!,flowerCount:0},context:{winSource:'self-draw',resolvedWinEvent:'none',lastVisibleCopy:false}});const fan=(i:McrScoringInput,s:string)=>detectMcr2006Fans(i).candidates.filter(x=>x.bindingId===`mcr2006.fan.${s}`);
  const shifted=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('dots',2),t('dots',3),t('dots',4),t('bamboo',3),t('bamboo',4),t('bamboo',5),t('dots',5),t('dots',5)]);const s=fan(shifted,'mixed-shifted-chows');expect(s).toHaveLength(2);expect(new Set(s.map(x=>x.id)).size).toBe(2);expect(new Set(s.map(x=>x.interpretationId)).size).toBe(1);expect(s.every(x=>x.value===6&&x.sourceLocator?.includes('§3.8.1'))).toBe(true);
  const types=mk([t('characters',1),t('characters',2),t('characters',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('dots',7),t('dots',8),t('dots',9),w('east'),w('east'),w('east'),w('south'),w('south')]);expect(fan(types,'all-types')).toHaveLength(0);
  const dragons=mk([d('red'),d('red'),d('red'),d('green'),d('green'),d('green'),d('white'),d('white'),d('white'),t('characters',1),t('characters',2),t('characters',3),t('dots',5),t('dots',5)]);const pairs=fan(dragons,'two-dragon-pungs');expect(pairs).toHaveLength(3);expect(new Set(pairs.map(x=>x.id)).size).toBe(3);expect(pairs.every(x=>x.value===6)).toBe(true);
  const outside=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',7),t('dots',8),t('dots',9),w('east'),w('east'),w('east'),t('bamboo',9),t('bamboo',9),t('bamboo',9),t('characters',5),t('characters',5)]);expect(fan(outside,'outside-hand')).toHaveLength(0);
  const ambiguous=mk([t('characters',1),t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',3),t('characters',4),t('characters',4),t('characters',4),t('characters',5),t('characters',5)]);const ar=detectMcr2006Fans(ambiguous);expect(ar.interpretations.filter(x=>x.kind==='ordinary').length).toBeGreaterThan(1);const fc=fan(ambiguous,'fully-concealed-hand');expect(fc).toHaveLength(1);expect(fc[0]).toMatchObject({interpretationId:'hand',value:4});
 });
 it('proves the #57 melded/concealed Kong source bridge',()=>{
  const hand=(groups:McrScoringInput['evidence']['fixedGroups']):McrScoringInput=>({evidence:{fixedGroups:groups,freeTiles:[t('bamboo',3),t('bamboo',4),t('bamboo',5),w('east'),w('east'),w('east'),t('characters',5),t('characters',5)],winningTile:t('characters',5),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}});const kong=(s:'characters'|'dots'|'bamboo',r:number,exposure:'melded'|'concealed')=>({kind:'kong' as const,exposure,tiles:[t(s,r),t(s,r),t(s,r),t(s,r)]});const get=(i:McrScoringInput,s:string)=>detectMcr2006Fans(i).candidates.filter(x=>x.bindingId===`mcr2006.fan.${s}`);
  const mm=hand([kong('characters',1,'melded'),kong('dots',2,'melded')]),a=get(mm,'two-melded-kongs');expect(detectMcr2006Fans(mm).interpretations.some(x=>x.kind==='ordinary')).toBe(true);expect(a).toHaveLength(1);expect(a[0]!.value).toBe(4);expect(a[0]!.sourceLocator).toContain('§3.8.1');expect(MCR_2006_FAN_BINDINGS.find(x=>x.id==='mcr2006.fan.two-melded-kongs')?.stage).toBe('candidate');
  const mc=hand([kong('characters',1,'melded'),kong('dots',2,'concealed')]),b=get(mc,'two-melded-kongs'),c=get(mc,'concealed-kong');expect(b).toHaveLength(1);expect(b[0]!.value).toBe(4);expect(c).toHaveLength(1);expect(c[0]!.value).toBe(2);
  const cc=hand([kong('characters',1,'concealed'),kong('dots',2,'concealed')]);expect(get(cc,'two-melded-kongs')).toHaveLength(0);expect(get(cc,'two-concealed-kongs')).toHaveLength(1);
  const three: McrScoringInput={evidence:{fixedGroups:[kong('characters',1,'melded'),kong('dots',2,'melded'),kong('bamboo',3,'concealed')],freeTiles:[t('characters',4),t('characters',5),t('characters',6),t('dots',5),t('dots',5)],winningTile:t('dots',5),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}};const d=get(three,'two-melded-kongs');expect(d).toHaveLength(3);expect(new Set(d.map(x=>x.id)).size).toBe(3);expect(d.every(x=>x.value===4&&x.sourceLocator?.includes('§3.8.1'))).toBe(true);
 });
 it('closes remaining 53/55/56/58/59/60 boundaries',()=>{
  const mk=(x:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles:x,winningTile:x.at(-1)!,flowerCount:0},context:{winSource:'self-draw',resolvedWinEvent:'none',lastVisibleCopy:false}});const f=(i:McrScoringInput,s:string)=>detectMcr2006Fans(i).candidates.filter(x=>x.bindingId===`mcr2006.fan.${s}`);
  const outside=mk([t('characters',2),t('characters',3),t('characters',4),t('dots',7),t('dots',8),t('dots',9),w('east'),w('east'),w('east'),t('bamboo',9),t('bamboo',9),t('bamboo',9),d('red'),d('red')]);expect(detectMcr2006Fans(outside).interpretations.some(x=>x.kind==='ordinary')).toBe(true);expect(f(outside,'outside-hand')).toHaveLength(0);
  const concealed=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('dots',5),t('dots',5)]);concealed.evidence.fixedGroups=[{kind:'kong',exposure:'concealed',tiles:[t('characters',9),t('characters',9),t('characters',9),t('characters',9)]}];const a=f(concealed,'fully-concealed-hand');expect(a).toHaveLength(1);expect(a[0]).toMatchObject({interpretationId:'hand',value:4});const melded={...concealed,evidence:{...concealed.evidence,fixedGroups:[{kind:'chow' as const,exposure:'melded' as const,tiles:[t('characters',1),t('characters',2),t('characters',3)]}]}};expect(f(melded,'fully-concealed-hand')).toHaveLength(0);
  const dragons=mk([d('red'),d('red'),d('red'),d('green'),d('green'),d('green'),t('characters',1),t('characters',2),t('characters',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('dots',5),t('dots',5)]),dp=f(dragons,'dragon-pung');expect(dp).toHaveLength(2);expect(new Set(dp.map(x=>x.id)).size).toBe(2);expect(dp.every(x=>x.value===2&&x.sourceLocator?.includes('§3.8.1'))).toBe(true);
  const wind=base();wind.evidence.freeTiles=[w('east'),w('east'),w('east'),t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',5),t('characters',5)];wind.evidence.winningTile=t('characters',5);wind.context.prevailingWind='east';const pw=f(wind,'prevalent-wind');expect(pw).toHaveLength(1);expect(pw[0]!.interpretationId).toMatch(/^ordinary:/);delete wind.context.prevailingWind;expect(f(wind,'prevalent-wind')).toHaveLength(0);expect(detectMcr2006Fans(wind).missingEvidenceIds).toContain('evidence.round-wind');
 });
 it('proves rows 51–60 candidate identities at their source routes',()=>{
  const fan=(input:McrScoringInput,slug:string)=>detectMcr2006Fans(input).candidates.filter(x=>x.bindingId===`mcr2006.fan.${slug}`);
  const stage=(slug:string)=>expect(MCR_2006_FAN_BINDINGS.find(x=>x.id===`mcr2006.fan.${slug}`)?.stage).toBe('candidate');
  const mk=(freeTiles:McrScoringInput['evidence']['freeTiles']):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles,winningTile:freeTiles.at(-1)!,flowerCount:0},context:{winSource:'self-draw',resolvedWinEvent:'none',lastVisibleCopy:false}});

  const shifted=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('dots',2),t('dots',3),t('dots',4),t('bamboo',3),t('bamboo',4),t('bamboo',5),t('dots',5),t('dots',5)]);
  const shiftedCandidates=fan(shifted,'mixed-shifted-chows'); expect(shiftedCandidates).toHaveLength(2); expect(shiftedCandidates.every(x=>x.value===6&&x.sourceLocator?.includes('§3.8.1')&&x.interpretationId.startsWith('ordinary:')&&x.id.startsWith(`${x.bindingId}#${x.interpretationId}#`))).toBe(true); expect(new Set(shiftedCandidates.map(x=>x.id.slice(`${x.bindingId}#${x.interpretationId}#`.length))).size).toBe(2); stage('mixed-shifted-chows');

  const types=mk([t('characters',1),t('characters',2),t('characters',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('dots',7),t('dots',8),t('dots',9),w('east'),w('east'),w('east'),d('red'),d('red')]);
  const allTypes=fan(types,'all-types'); expect(allTypes).toHaveLength(1); expect(allTypes[0]).toMatchObject({value:6}); expect(allTypes[0]!.sourceLocator).toContain('§3.8.1'); expect(allTypes[0]!.interpretationId).toMatch(/^ordinary:/); expect(allTypes[0]!.id).toBe(`${allTypes[0]!.bindingId}#${allTypes[0]!.interpretationId}#match`); stage('all-types');

  const melded:McrScoringInput={evidence:{fixedGroups:[{kind:'chow',exposure:'melded',tiles:[t('characters',1),t('characters',2),t('characters',3)]},{kind:'chow',exposure:'melded',tiles:[t('dots',4),t('dots',5),t('dots',6)]},{kind:'chow',exposure:'melded',tiles:[t('bamboo',7),t('bamboo',8),t('bamboo',9)]},{kind:'pung',exposure:'melded',tiles:[w('east'),w('east'),w('east')]}],freeTiles:[d('red'),d('red')],winningTile:d('red'),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}};
  const meldedCandidate=fan(melded,'melded-hand'); expect(meldedCandidate).toHaveLength(1); expect(meldedCandidate[0]).toMatchObject({value:6}); expect(meldedCandidate[0]!.sourceLocator).toContain('§3.8.1'); expect(meldedCandidate[0]!.interpretationId).toMatch(/^ordinary:/); expect(meldedCandidate[0]!.id).toBe(`${meldedCandidate[0]!.bindingId}#${meldedCandidate[0]!.interpretationId}#pair`); stage('melded-hand');
  const concealedKong={...melded,evidence:{...melded.evidence,fixedGroups:[...melded.evidence.fixedGroups.slice(0,3),{kind:'kong' as const,exposure:'concealed' as const,tiles:[w('east'),w('east'),w('east'),w('east')]}]}}; expect(detectMcr2006Fans(concealedKong).interpretations.some(x=>x.kind==='ordinary')).toBe(true); expect(fan(concealedKong,'melded-hand')).toHaveLength(0);

  const dragons=mk([d('red'),d('red'),d('red'),d('green'),d('green'),d('green'),d('white'),d('white'),d('white'),t('characters',1),t('characters',2),t('characters',3),t('dots',5),t('dots',5)]);
  const twoDragonPungs=fan(dragons,'two-dragon-pungs'); expect(twoDragonPungs).toHaveLength(3); expect(twoDragonPungs.every(x=>x.value===6&&x.sourceLocator?.includes('§3.8.1')&&x.interpretationId.startsWith('ordinary:')&&x.id.startsWith(`${x.bindingId}#${x.interpretationId}#`))).toBe(true); expect(new Set(twoDragonPungs.map(x=>x.interpretationId)).size).toBe(1); expect(new Set(twoDragonPungs.map(x=>x.id.slice(`${x.bindingId}#${x.interpretationId}#`.length))).size).toBe(3); stage('two-dragon-pungs');

  const outside=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',7),t('dots',8),t('dots',9),w('east'),w('east'),w('east'),t('bamboo',9),t('bamboo',9),t('bamboo',9),d('red'),d('red')]);
  const outsideHand=fan(outside,'outside-hand'); expect(outsideHand).toHaveLength(1); expect(outsideHand[0]).toMatchObject({value:4}); expect(outsideHand[0]!.sourceLocator).toContain('§3.8.1'); expect(outsideHand[0]!.interpretationId).toMatch(/^ordinary:/); expect(outsideHand[0]!.id).toBe(`${outsideHand[0]!.bindingId}#${outsideHand[0]!.interpretationId}#match`); stage('outside-hand');

  const concealed=base(); const fullyConcealed=fan(concealed,'fully-concealed-hand'); expect(fullyConcealed).toHaveLength(1); expect(fullyConcealed[0]!.sourceLocator).toContain('§3.8.1'); expect(fullyConcealed[0]!.interpretationId).toBe('hand'); expect(fullyConcealed[0]!.id).toContain('mcr2006.fan.fully-concealed-hand#hand#hand'); stage('fully-concealed-hand');

  const lastTrue=base(); lastTrue.context.lastVisibleCopy=true; const lastTile=fan(lastTrue,'last-tile'); expect(lastTile).toHaveLength(1); expect(lastTile[0]).toMatchObject({value:4,interpretationId:'context'}); expect(lastTile[0]!.sourceLocator).toContain('§3.8.1'); expect(lastTile[0]!.id).toBe(`${lastTile[0]!.bindingId}#context#dots:5`); stage('last-tile'); const lastFalse=base(); expect(fan(lastFalse,'last-tile')).toHaveLength(0); const lastUnknown=base(); delete lastUnknown.context.lastVisibleCopy; expect(fan(lastUnknown,'last-tile')).toHaveLength(0); expect(detectMcr2006Fans(lastUnknown).missingEvidenceIds).toContain('evidence.last-visible-copy');

  const dragonPungHand=mk([d('red'),d('red'),d('red'),d('green'),d('green'),d('green'),t('characters',1),t('characters',2),t('characters',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('dots',5),t('dots',5)]); const dragonPungs=fan(dragonPungHand,'dragon-pung'); expect(dragonPungs).toHaveLength(2); expect(dragonPungs.every(x=>x.value===2&&x.sourceLocator?.includes('§3.8.1')&&x.interpretationId.startsWith('ordinary:'))).toBe(true); expect(new Set(dragonPungs.map(x=>x.interpretationId)).size).toBe(1); expect(dragonPungs.some(x=>x.id.endsWith('#free:set:2:dragon:green'))).toBe(true); expect(dragonPungs.some(x=>x.id.endsWith('#free:set:3:dragon:red'))).toBe(true); stage('dragon-pung');

  const wind=mk([w('east'),w('east'),w('east'),t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',5),t('characters',5)]); wind.context.prevailingWind='east'; const prevalent=fan(wind,'prevalent-wind'); expect(prevalent).toHaveLength(1); expect(prevalent[0]).toMatchObject({value:2}); expect(prevalent[0]!.sourceLocator).toContain('§3.8.1'); expect(prevalent[0]!.interpretationId).toMatch(/^ordinary:/); expect(prevalent[0]!.id).toBe(`${prevalent[0]!.bindingId}#${prevalent[0]!.interpretationId}#free:set:3:wind:east`); stage('prevalent-wind'); wind.context.prevailingWind='south'; expect(fan(wind,'prevalent-wind')).toHaveLength(0); delete wind.context.prevailingWind; expect(fan(wind,'prevalent-wind')).toHaveLength(0); expect(detectMcr2006Fans(wind).missingEvidenceIds).toContain('evidence.round-wind');
 });
 it('proves rows 61–70 candidate routes, multiplicities, and identities',()=>{
  const fan=(input:McrScoringInput,slug:string)=>detectMcr2006Fans(input).candidates.filter(x=>x.bindingId===`mcr2006.fan.${slug}`);
  const stage=(slug:string)=>expect(MCR_2006_FAN_BINDINGS.find(x=>x.id===`mcr2006.fan.${slug}`)?.stage).toBe('candidate');
  const mk=(freeTiles:McrScoringInput['evidence']['freeTiles'],context:Partial<McrScoringInput['context']>={}):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles,winningTile:freeTiles.at(-1)!,flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false,...context}});
  const checked=(input:McrScoringInput,slug:string,value:number)=>{const candidates=fan(input,slug); expect(candidates.every(x=>x.value===value&&x.sourceLocator?.includes('§3.8.1')&&x.id.startsWith(`${x.bindingId}#${x.interpretationId}#`))).toBe(true); stage(slug); return candidates;};

  const southWind=mk([w('south'),w('south'),w('south'),t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',5),t('characters',5)],{seatWind:'south'}); const seat=checked(southWind,'seat-wind',2); expect(seat).toHaveLength(1); expect(seat[0]!.interpretationId).toMatch(/^ordinary:/); expect(seat[0]!.id).toBe(`${seat[0]!.bindingId}#${seat[0]!.interpretationId}#free:set:3:wind:south`); southWind.context.seatWind='east'; expect(fan(southWind,'seat-wind')).toHaveLength(0); delete southWind.context.seatWind; expect(fan(southWind,'seat-wind')).toHaveLength(0); expect(detectMcr2006Fans(southWind).missingEvidenceIds).toContain('evidence.seat-wind');
  const coincident=mk([w('east'),w('east'),w('east'),t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',5),t('characters',5)],{seatWind:'east',prevailingWind:'east'}); const coincidentSeat=checked(coincident,'seat-wind',2),coincidentPrevalent=checked(coincident,'prevalent-wind',2); expect(coincidentSeat).toHaveLength(1); expect(coincidentPrevalent).toHaveLength(1); expect(coincidentSeat[0]!.id.split('#').at(-1)).toBe('free:set:3:wind:east'); expect(coincidentPrevalent[0]!.id.split('#').at(-1)).toBe('free:set:3:wind:east');

  const ambiguous=mk([t('characters',1),t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',3),t('characters',4),t('characters',4),t('characters',4),t('characters',5),t('characters',5)]); const ambiguousResult=detectMcr2006Fans(ambiguous); expect(ambiguousResult.interpretations.filter(x=>x.kind==='ordinary').length).toBeGreaterThan(1); const concealedHand=checked(ambiguous,'concealed-hand',2); expect(concealedHand).toHaveLength(1); expect(concealedHand[0]!.interpretationId).toBe('hand'); expect(concealedHand[0]!.id).toBe('mcr2006.fan.concealed-hand#hand#hand');
  const concealedKong=mk([t('dots',1),t('dots',2),t('dots',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('characters',7),t('characters',8),t('characters',9),t('dots',2),t('dots',2)]); concealedKong.evidence.fixedGroups=[{kind:'kong',exposure:'concealed',tiles:[t('characters',5),t('characters',5),t('characters',5),t('characters',5)]}]; expect(checked(concealedKong,'concealed-hand',2)).toHaveLength(1); const meldedGroup={...concealedKong,evidence:{...concealedKong.evidence,fixedGroups:[{kind:'chow' as const,exposure:'melded' as const,tiles:[t('characters',1),t('characters',2),t('characters',3)]}]}}; expect(fan(meldedGroup,'concealed-hand')).toHaveLength(0); const concealedSelf={...ambiguous,context:{...ambiguous.context,winSource:'self-draw' as const}}; expect(fan(concealedSelf,'concealed-hand')).toHaveLength(0);

  const allChow=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',4),t('characters',5),t('characters',6),t('dots',2),t('dots',2)]); const allChows=checked(allChow,'all-chows',2); expect(allChows).toHaveLength(1); expect(allChows[0]!.interpretationId).toMatch(/^ordinary:/); expect(allChows[0]!.id).toBe(`${allChows[0]!.bindingId}#${allChows[0]!.interpretationId}#match`); const allChowInterpretation=detectMcr2006Fans(allChow).interpretations.find(x=>x.id===allChows[0]!.interpretationId)!; expect(allChowInterpretation.elements.filter(x=>x.kind==='chow')).toHaveLength(4); expect(allChowInterpretation.elements.find(x=>x.kind==='pair')!.faces[0]).toBe('dots:2'); const honorPair={...allChow,evidence:{...allChow.evidence,freeTiles:[...allChow.evidence.freeTiles.slice(0,12),w('east'),w('east')],winningTile:w('east')}}; expect(fan(honorPair,'all-chows')).toHaveLength(0); const pungHand={...allChow,evidence:{...allChow.evidence,freeTiles:[...allChow.evidence.freeTiles.slice(0,9),t('characters',4),t('characters',4),t('characters',4),t('dots',2),t('dots',2)],winningTile:t('dots',2)}}; expect(fan(pungHand,'all-chows')).toHaveLength(0);

  const hog=mk([t('characters',3),t('characters',4),t('characters',5),t('characters',5),t('characters',5),t('dots',1),t('dots',2),t('dots',3),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('dots',2),t('dots',2),t('characters',5)]); const tileHog=checked(hog,'tile-hog',2); expect(tileHog).toHaveLength(1); expect(tileHog[0]!.interpretationId).toBe('hand'); expect(tileHog[0]!.id).toBe('mcr2006.fan.tile-hog#hand#characters:5'); const hogKong=mk([t('dots',1),t('dots',2),t('dots',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('characters',7),t('characters',8),t('characters',9),t('dots',2),t('dots',2)]); hogKong.evidence.fixedGroups=[{kind:'kong',exposure:'concealed',tiles:[t('characters',5),t('characters',5),t('characters',5),t('characters',5)]}]; expect(fan(hogKong,'tile-hog')).toHaveLength(0); const twoHog=mk([t('characters',2),t('characters',3),t('characters',4),t('characters',2),t('characters',2),t('characters',4),t('characters',5),t('characters',6),t('characters',5),t('characters',5),t('characters',5),t('dots',7),t('dots',7),t('characters',2)]); const twoHogs=checked(twoHog,'tile-hog',2); expect(twoHogs.map(x=>x.id)).toEqual(['mcr2006.fan.tile-hog#hand#characters:2','mcr2006.fan.tile-hog#hand#characters:5']);

  const doublePung=mk([t('characters',5),t('characters',5),t('characters',5),t('dots',5),t('dots',5),t('dots',5),t('bamboo',5),t('bamboo',5),t('bamboo',5),t('characters',1),t('characters',2),t('characters',3),t('dots',2),t('dots',2)]); const doublePungs=checked(doublePung,'double-pung',2); expect(doublePungs).toHaveLength(3); expect(new Set(doublePungs.map(x=>x.interpretationId)).size).toBe(1); const doublePungPrefix=`mcr2006.fan.double-pung#${doublePungs[0]!.interpretationId}#`; expect(doublePungs.map(x=>x.id)).toEqual([`${doublePungPrefix}free:set:0:bamboo:5+free:set:2:characters:5`,`${doublePungPrefix}free:set:0:bamboo:5+free:set:3:dots:5`,`${doublePungPrefix}free:set:2:characters:5+free:set:3:dots:5`]);

  const concealedPungs=mk([t('characters',5),t('characters',5),t('characters',5),t('dots',6),t('dots',6),t('dots',6),t('bamboo',7),t('bamboo',7),t('bamboo',7),t('characters',1),t('characters',2),t('characters',3),t('dots',2),t('dots',2)]); const twoConcealed=checked(concealedPungs,'two-concealed-pungs',2); expect(twoConcealed).toHaveLength(3); expect(new Set(twoConcealed.map(x=>x.interpretationId)).size).toBe(1); const twoConcealedPrefix=`mcr2006.fan.two-concealed-pungs#${twoConcealed[0]!.interpretationId}#`; expect(twoConcealed.map(x=>x.id)).toEqual([`${twoConcealedPrefix}free:set:0:bamboo:7+free:set:2:characters:5`,`${twoConcealedPrefix}free:set:0:bamboo:7+free:set:3:dots:6`,`${twoConcealedPrefix}free:set:2:characters:5+free:set:3:dots:6`]);
  const concealedBridge=mk([t('dots',6),t('dots',6),t('dots',6),t('bamboo',1),t('bamboo',2),t('bamboo',3),t('characters',7),t('characters',8),t('characters',9),t('bamboo',2),t('bamboo',2)]); concealedBridge.evidence.fixedGroups=[{kind:'kong',exposure:'concealed',tiles:[t('characters',5),t('characters',5),t('characters',5),t('characters',5)]}]; const bridge=checked(concealedBridge,'two-concealed-pungs',2); expect(bridge).toHaveLength(1); expect(bridge[0]!.id).toBe(`${bridge[0]!.bindingId}#${bridge[0]!.interpretationId}#fixed:kong:concealed:characters:5,characters:5,characters:5,characters:5:0+free:set:2:dots:6`); const meldedPung={...concealedBridge,evidence:{...concealedBridge.evidence,fixedGroups:[{kind:'pung' as const,exposure:'melded' as const,tiles:[t('characters',5),t('characters',5),t('characters',5)]}]}}; expect(fan(meldedPung,'two-concealed-pungs')).toHaveLength(0);

  const oneKong=hogKong; const concealedKongs=checked(oneKong,'concealed-kong',2); expect(concealedKongs).toHaveLength(1); expect(concealedKongs[0]!.id).toBe(`${concealedKongs[0]!.bindingId}#${concealedKongs[0]!.interpretationId}#fixed:kong:concealed:characters:5,characters:5,characters:5,characters:5:0`); const twoKong=mk([t('bamboo',1),t('bamboo',2),t('bamboo',3),t('characters',7),t('characters',8),t('characters',9),t('bamboo',2),t('bamboo',2)]); twoKong.evidence.fixedGroups=[{kind:'kong',exposure:'concealed',tiles:[t('characters',5),t('characters',5),t('characters',5),t('characters',5)]},{kind:'kong',exposure:'concealed',tiles:[t('dots',6),t('dots',6),t('dots',6),t('dots',6)]}]; const twoKongs=checked(twoKong,'concealed-kong',2); expect(twoKongs).toHaveLength(2); expect(twoKongs.map(x=>x.id.split('#').at(-1))).toEqual(['fixed:kong:concealed:characters:5,characters:5,characters:5,characters:5:0','fixed:kong:concealed:dots:6,dots:6,dots:6,dots:6:0']); const meldedKong={...oneKong,evidence:{...oneKong.evidence,fixedGroups:[{kind:'kong' as const,exposure:'melded' as const,tiles:[t('characters',5),t('characters',5),t('characters',5),t('characters',5)]}]}}; expect(fan(meldedKong,'concealed-kong')).toHaveLength(0);

  const simples=mk([t('characters',2),t('characters',3),t('characters',4),t('dots',3),t('dots',4),t('dots',5),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('characters',6),t('characters',6),t('characters',6),t('dots',5),t('dots',5)]); expect(simples.evidence.freeTiles.every(x=>x.face.family==='suit'&&x.face.rank>=2&&x.face.rank<=8)).toBe(true); const allSimples=checked(simples,'all-simples',2); expect(allSimples).toHaveLength(1); expect(allSimples[0]!.interpretationId).toBe('hand'); expect(allSimples[0]!.id).toBe('mcr2006.fan.all-simples#hand#hand'); const terminal={...simples,evidence:{...simples.evidence,freeTiles:[t('characters',1),...simples.evidence.freeTiles.slice(1)],winningTile:simples.evidence.winningTile}}; expect(fan(terminal,'all-simples')).toHaveLength(0); const honor={...simples,evidence:{...simples.evidence,freeTiles:[...simples.evidence.freeTiles.slice(0,12),w('east'),w('east')],winningTile:w('east')}}; expect(fan(honor,'all-simples')).toHaveLength(0);

  const pure=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',2),t('bamboo',2)]); const pureDouble=checked(pure,'pure-double-chow',1); const pureInterpretation=[...new Set(pureDouble.map(x=>x.interpretationId))].find(id=>pureDouble.filter(x=>x.interpretationId===id).length===3)!; const pureGroup=pureDouble.filter(x=>x.interpretationId===pureInterpretation); expect(pureGroup).toHaveLength(3); const purePrefix=`mcr2006.fan.pure-double-chow#${pureInterpretation}#`; expect(pureGroup.map(x=>x.id)).toEqual([`${purePrefix}free:set:0:characters:1+free:set:1:characters:1`,`${purePrefix}free:set:0:characters:1+free:set:2:characters:1`,`${purePrefix}free:set:1:characters:1+free:set:2:characters:1`]);

  const mixed=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',1),t('dots',2),t('dots',3),t('bamboo',1),t('bamboo',2),t('bamboo',3),t('characters',4),t('characters',5),t('characters',6),t('dots',2),t('dots',2)]); const mixedDouble=checked(mixed,'mixed-double-chow',1); expect(mixedDouble).toHaveLength(3); expect(new Set(mixedDouble.map(x=>x.interpretationId)).size).toBe(1); const mixedPrefix=`mcr2006.fan.mixed-double-chow#${mixedDouble[0]!.interpretationId}#`; expect(mixedDouble.map(x=>x.id)).toEqual([`${mixedPrefix}free:set:0:bamboo:1+free:set:1:characters:1`,`${mixedPrefix}free:set:0:bamboo:1+free:set:3:dots:1`,`${mixedPrefix}free:set:1:characters:1+free:set:3:dots:1`]);
 });
 it('proves rows 71–81 candidate routes, waits, and post-qualification boundary',()=>{
  const fan=(input:McrScoringInput,slug:string)=>detectMcr2006Fans(input).candidates.filter(x=>x.bindingId===`mcr2006.fan.${slug}`);
  const stage=(slug:string)=>expect(MCR_2006_FAN_BINDINGS.find(x=>x.id===`mcr2006.fan.${slug}`)?.stage).toBe('candidate');
  const mk=(freeTiles:McrScoringInput['evidence']['freeTiles'],context:Partial<McrScoringInput['context']>={}):McrScoringInput=>({evidence:{fixedGroups:[],freeTiles,winningTile:freeTiles.at(-1)!,flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false,...context}});
  const checked=(input:McrScoringInput,slug:string,value:number)=>{const candidates=fan(input,slug); expect(candidates.every(x=>x.value===value&&x.sourceLocator?.includes('§3.8.1')&&x.id.startsWith(`${x.bindingId}#${x.interpretationId}#`))).toBe(true); stage(slug); return candidates;};

  const shortPositive=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',4),t('characters',5),t('characters',6),t('dots',7),t('dots',8),t('dots',9),t('bamboo',2),t('bamboo',2),t('bamboo',2),t('dots',5),t('dots',5)]); const oneShort=checked(shortPositive,'short-straight',1); expect(oneShort).toHaveLength(1); expect(oneShort[0]!.id).toBe(`${oneShort[0]!.bindingId}#${oneShort[0]!.interpretationId}#free:set:1:characters:1+free:set:2:characters:4`); const short=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',4),t('characters',5),t('characters',6),t('characters',7),t('characters',8),t('characters',9),t('bamboo',2),t('bamboo',2),t('bamboo',2),t('dots',5),t('dots',5)]); const shortStraights=checked(short,'short-straight',1); expect(shortStraights).toHaveLength(2); const shortIid=shortStraights[0]!.interpretationId; expect(shortStraights.every(x=>x.interpretationId===shortIid)).toBe(true); const shortPrefix=`mcr2006.fan.short-straight#${shortIid}#`; expect(shortStraights.map(x=>x.id)).toEqual([`${shortPrefix}free:set:1:characters:1+free:set:2:characters:4`,`${shortPrefix}free:set:2:characters:4+free:set:3:characters:7`]);

  const terminalPositive=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',7),t('characters',8),t('characters',9),t('dots',4),t('dots',5),t('dots',6),t('bamboo',2),t('bamboo',2),t('bamboo',2),t('dots',5),t('dots',5)]); const oneTerminal=checked(terminalPositive,'two-terminal-chows',1); expect(oneTerminal).toHaveLength(1); expect(oneTerminal[0]!.id).toBe(`${oneTerminal[0]!.bindingId}#${oneTerminal[0]!.interpretationId}#free:set:1:characters:1+free:set:2:characters:7`); const terminals=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('characters',7),t('characters',8),t('characters',9),t('characters',7),t('characters',8),t('characters',9),t('dots',5),t('dots',5)]); const terminalChows=checked(terminals,'two-terminal-chows',1); expect(terminalChows).toHaveLength(4); const terminalIid=terminalChows[0]!.interpretationId; expect(terminalChows.every(x=>x.interpretationId===terminalIid)).toBe(true); const terminalPrefix=`mcr2006.fan.two-terminal-chows#${terminalIid}#`; expect(terminalChows.map(x=>x.id)).toEqual([`${terminalPrefix}free:set:0:characters:1+free:set:2:characters:7`,`${terminalPrefix}free:set:0:characters:1+free:set:3:characters:7`,`${terminalPrefix}free:set:1:characters:1+free:set:2:characters:7`,`${terminalPrefix}free:set:1:characters:1+free:set:3:characters:7`]);

  const terminalPungs=mk([t('characters',1),t('characters',1),t('characters',1),t('dots',9),t('dots',9),t('dots',9),w('east'),w('east'),w('east'),d('red'),d('red'),d('red'),t('bamboo',5),t('bamboo',5)]); const terminalOrHonor=checked(terminalPungs,'pung-terminals-or-honors',1); expect(terminalOrHonor).toHaveLength(3); expect(new Set(terminalOrHonor.map(x=>x.interpretationId)).size).toBe(1); const terminalPungPrefix=`mcr2006.fan.pung-terminals-or-honors#${terminalOrHonor[0]!.interpretationId}#`; expect(terminalOrHonor.map(x=>x.id)).toEqual([`${terminalPungPrefix}free:set:0:characters:1`,`${terminalPungPrefix}free:set:1:dots:9`,`${terminalPungPrefix}free:set:3:wind:east`]); expect(fan(terminalPungs,'dragon-pung').some(x=>x.id.endsWith('#free:set:2:dragon:red'))).toBe(true);

  const meldedKong=mk([t('dots',1),t('dots',2),t('dots',3),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('characters',7),t('characters',8),t('characters',9),t('dots',2),t('dots',2)]); meldedKong.evidence.fixedGroups=[{kind:'kong',exposure:'melded',tiles:[t('characters',5),t('characters',5),t('characters',5),t('characters',5)]}]; const oneMelded=checked(meldedKong,'melded-kong',1); expect(oneMelded).toHaveLength(1); expect(oneMelded[0]!.id).toBe(`${oneMelded[0]!.bindingId}#${oneMelded[0]!.interpretationId}#fixed:kong:melded:characters:5,characters:5,characters:5,characters:5:0`); const multipleMelded=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',2),t('dots',2)]); multipleMelded.evidence.fixedGroups=[{kind:'kong',exposure:'melded',tiles:[t('characters',5),t('characters',5),t('characters',5),t('characters',5)]},{kind:'kong',exposure:'melded',tiles:[t('dots',6),t('dots',6),t('dots',6),t('dots',6)]},{kind:'kong',exposure:'concealed',tiles:[t('bamboo',7),t('bamboo',7),t('bamboo',7),t('bamboo',7)]}]; const twoMelded=checked(multipleMelded,'melded-kong',1); expect(twoMelded.map(x=>x.id.split('#').at(-1))).toEqual(['fixed:kong:melded:characters:5,characters:5,characters:5,characters:5:0','fixed:kong:melded:dots:6,dots:6,dots:6,dots:6:0']);

  const voided=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',4),t('characters',5),t('characters',6),t('dots',7),t('dots',8),t('dots',9),t('dots',7),t('dots',7),t('dots',7),w('east'),w('east')]); const oneVoided=checked(voided,'one-voided-suit',1); expect(oneVoided).toHaveLength(1); expect(oneVoided[0]!.interpretationId).toBe('hand'); expect(oneVoided[0]!.id).toBe('mcr2006.fan.one-voided-suit#hand#hand'); const threeSuits=base(); expect(fan(threeSuits,'one-voided-suit')).toHaveLength(0); const oneSuit=mk([t('characters',1),t('characters',2),t('characters',3),t('characters',4),t('characters',5),t('characters',6),t('characters',7),t('characters',8),t('characters',9),w('east'),w('east'),w('east'),t('characters',5),t('characters',5)]); expect(fan(oneSuit,'one-voided-suit')).toHaveLength(0);

  const noHonors=mk([t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),t('characters',7),t('characters',7),t('characters',7),t('dots',5),t('dots',5)]); expect(noHonors.evidence.freeTiles.every(x=>x.face.family==='suit')).toBe(true); const noHonorCandidates=checked(noHonors,'no-honors',1); expect(noHonorCandidates).toHaveLength(1); expect(noHonorCandidates[0]!.interpretationId).toBe('hand'); expect(noHonorCandidates[0]!.id).toBe('mcr2006.fan.no-honors#hand#hand'); const honors={...noHonors,evidence:{...noHonors.evidence,freeTiles:[...noHonors.evidence.freeTiles.slice(0,12),w('east'),w('east')],winningTile:w('east')}}; expect(fan(honors,'no-honors')).toHaveLength(0);

  const fixedWait=[{kind:'chow' as const,exposure:'melded' as const,tiles:[t('dots',1),t('dots',2),t('dots',3)]},{kind:'pung' as const,exposure:'melded' as const,tiles:[t('bamboo',5),t('bamboo',5),t('bamboo',5)]},{kind:'pung' as const,exposure:'melded' as const,tiles:[w('east'),w('east'),w('east')]}]; const edge: McrScoringInput={evidence:{fixedGroups:fixedWait,freeTiles:[t('characters',1),t('characters',2),t('characters',3),t('dots',7),t('dots',7)],winningTile:t('characters',3),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}}; const edgeWait=checked(edge,'edge-wait',1); expect(edgeWait).toHaveLength(1); expect(edgeWait[0]!.interpretationId).toMatch(/^ordinary:/); expect(edgeWait[0]!.id).toBe(`${edgeWait[0]!.bindingId}#${edgeWait[0]!.interpretationId}#winning-role`); const multiFace={...edge,evidence:{...edge.evidence,winningTile:t('characters',1)}}; expect(fan(multiFace,'edge-wait')).toHaveLength(0);
  const closed={...edge,evidence:{...edge.evidence,freeTiles:[t('characters',2),t('characters',3),t('characters',4),t('dots',7),t('dots',7)],winningTile:t('characters',3)}}; const closedWait=checked(closed,'closed-wait',1); expect(closedWait).toHaveLength(1); expect(closedWait[0]!.id).toBe(`${closedWait[0]!.bindingId}#${closedWait[0]!.interpretationId}#winning-role`); expect(fan(multiFace,'closed-wait')).toHaveLength(0);
  const single:McrScoringInput={evidence:{fixedGroups:[{kind:'chow',exposure:'melded',tiles:[t('characters',1),t('characters',2),t('characters',3)]},{kind:'chow',exposure:'melded',tiles:[t('dots',4),t('dots',5),t('dots',6)]},{kind:'chow',exposure:'melded',tiles:[t('bamboo',7),t('bamboo',8),t('bamboo',9)]},{kind:'pung',exposure:'melded',tiles:[w('east'),w('east'),w('east')]}],freeTiles:[t('dots',7),t('dots',7)],winningTile:t('dots',7),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}}; const singleWait=checked(single,'single-wait',1); expect(singleWait).toHaveLength(1); expect(singleWait[0]!.id).toBe(`${singleWait[0]!.bindingId}#${singleWait[0]!.interpretationId}#winning-role`); const competingSingle=base(); competingSingle.evidence.freeTiles=[t('characters',1),t('characters',1),t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',4),t('characters',5),t('characters',5),t('characters',5)]; competingSingle.evidence.winningTile=t('characters',5); expect(fan(competingSingle,'single-wait')).toHaveLength(0); const irregular=base(); irregular.evidence.freeTiles=[t('characters',1),t('characters',1),t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',3),t('characters',3),t('characters',6),t('characters',6)]; irregular.evidence.winningTile=t('characters',6); expect(fan(irregular,'single-wait')).toHaveLength(0);

  const self=base(); self.context.winSource='self-draw'; const selfDrawn=checked(self,'self-drawn',1); expect(selfDrawn).toHaveLength(1); expect(selfDrawn[0]).toMatchObject({interpretationId:'context'}); expect(selfDrawn[0]!.id).toBe('mcr2006.fan.self-drawn#context#self-draw'); const flower={...self,context:{...self.context,resolvedWinEvent:'flower-replacement' as const}}; expect(checked(flower,'self-drawn',1)).toHaveLength(1); expect(fan(flower,'out-with-replacement-tile')).toHaveLength(0); const replacement={...self,context:{...self.context,resolvedWinEvent:'kong-replacement' as const}}; expect(checked(replacement,'self-drawn',1)).toHaveLength(1); expect(checked(replacement,'out-with-replacement-tile',8)).toHaveLength(1); const discard={...self,context:{...self.context,winSource:'discard' as const,resolvedWinEvent:'none' as const}}; expect(fan(discard,'self-drawn')).toHaveLength(0);

  const flowerOne=base(); flowerOne.evidence.flowerCount=1; const flowerBinding=MCR_2006_FAN_BINDINGS.find(x=>x.id==='mcr2006.fan.flower-tiles')!; expect(flowerBinding).toMatchObject({value:1,stage:'post-qualification'}); expect(flowerBinding.sourceLocator).toContain('§3.8.1 #81'); expect(flowerBinding.sourceLocator).toContain('§3.11.6.6'); expect(fan(flowerOne,'flower-tiles')).toHaveLength(0); expect(detectMcr2006Fans(flowerOne).flowerCount).toBe(1); const flowerEight={...flowerOne,evidence:{...flowerOne.evidence,flowerCount:8}}; expect(fan(flowerEight,'flower-tiles')).toHaveLength(0); expect(detectMcr2006Fans(flowerEight).flowerCount).toBe(8); expect(MCR_2006_FAN_BINDINGS).toHaveLength(81); expect(MCR_2006_FAN_BINDINGS.every(x=>x.sourceLocator.length>0)).toBe(true); expect(MCR_2006_FAN_BINDINGS.find(x=>x.id==='mcr2006.fan.chicken-hand')?.stage).toBe('fallback');
 });
 it('rejects the pinned malformed terminal-Chow and competing wait routes',()=>{
  const malformed=base(); malformed.evidence.freeTiles=[t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('dots',7),t('dots',8),t('dots',9),t('dots',7),t('dots',8),t('dots',9),t('bamboo',5),t('bamboo',5)]; malformed.evidence.winningTile=t('bamboo',5); expect(ids(malformed)).not.toContain('mcr2006.fan.three-suited-terminal-chows');
  const competing=base(); competing.evidence.freeTiles=[t('characters',1),t('characters',1),t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',4),t('characters',5),t('characters',5),t('characters',5)]; competing.evidence.winningTile=t('characters',5); expect(ids(competing)).not.toContain('mcr2006.fan.single-wait');
  const irregular=base(); irregular.evidence.freeTiles=[t('characters',1),t('characters',1),t('characters',1),t('characters',1),t('characters',2),t('characters',2),t('characters',2),t('characters',2),t('characters',3),t('characters',3),t('characters',3),t('characters',3),t('characters',6),t('characters',6)]; irregular.evidence.winningTile=t('characters',6); expect(ids(irregular)).not.toContain('mcr2006.fan.single-wait');
 });
 it('pins all 81 source bindings with source locator and the two later-stage boundaries',()=>{
  expect(MCR_2006_FAN_BINDINGS).toHaveLength(81);
  expect(MCR_2006_FAN_BINDINGS.map(x=>x.id)).toEqual(Array.from({length:81},(_,i)=>`mcr2006.fan.${MCR_2006_FAN_BINDINGS[i]!.id.slice('mcr2006.fan.'.length)}`));
  expect(MCR_2006_FAN_BINDINGS.every(x=>x.sourceLocator.length>0)).toBe(true);
  expect(MCR_2006_FAN_BINDINGS.find(x=>x.id==='mcr2006.fan.chicken-hand')?.stage).toBe('fallback');
  expect(MCR_2006_FAN_BINDINGS.find(x=>x.id==='mcr2006.fan.flower-tiles')?.stage).toBe('post-qualification');
 });
 it('enumerates free tiles rather than treating a UI grouping as authoritative',()=>{
  const r=detectMcr2006Fans(base()); expect(r.interpretations.filter(x=>x.kind==='ordinary').length).toBeGreaterThan(0); expect(ids(base())).toContain('mcr2006.fan.self-drawn');
 });
 it('recognises Knitted Straight with the permitted fixed remaining set',()=>{
  const input:McrScoringInput={evidence:{fixedGroups:[{kind:'pung',exposure:'melded',tiles:[w('east'),w('east'),w('east')]}],freeTiles:[t('characters',1),t('characters',4),t('characters',7),t('bamboo',2),t('bamboo',5),t('bamboo',8),t('dots',3),t('dots',6),t('dots',9),d('red'),d('red')],winningTile:d('red'),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}};
  const matches=detectMcr2006Fans(input).candidates.filter(candidate=>candidate.bindingId==='mcr2006.fan.knitted-straight'); expect(matches).toHaveLength(1); expect(matches[0]!.interpretationId).toBe('knitted-straight:0');
 });
 it('keeps legal repeated occurrences distinct from their stable binding',()=>{
  const input=base(); input.evidence.freeTiles=[t('characters',5),t('characters',5),t('characters',5),t('dots',5),t('dots',5),t('dots',5),t('bamboo',5),t('bamboo',5),t('bamboo',5),t('characters',1),t('characters',2),t('characters',3),t('dots',2),t('dots',2)]; input.evidence.winningTile=t('dots',2);
  const matches=detectMcr2006Fans(input).candidates.filter(x=>x.bindingId==='mcr2006.fan.double-pung'); expect(matches.length).toBe(3); expect(new Set(matches.map(x=>x.id)).size).toBe(3);
 });
 it('uses the exact reversible set and rejects an excluded face',()=>{
  const input=base(); input.evidence.freeTiles=[t('dots',1),t('dots',2),t('dots',3),t('dots',3),t('dots',4),t('dots',5),t('bamboo',4),t('bamboo',5),t('bamboo',6),t('bamboo',8),t('bamboo',8),t('bamboo',8),{face:{family:'dragon',dragon:'white'}},{face:{family:'dragon',dragon:'white'}}]; input.evidence.winningTile={face:{family:'dragon',dragon:'white'}};
  expect(ids(input)).toContain('mcr2006.fan.reversible-tiles'); input.evidence.freeTiles=[t('bamboo',1),...input.evidence.freeTiles.slice(1)]; expect(ids(input)).not.toContain('mcr2006.fan.reversible-tiles');
 });
 it('keeps flower points and Chicken Hand outside ordinary candidates',()=>{
  const input=base(); input.evidence.flowerCount=8; const r=detectMcr2006Fans(input); expect(r.candidates.some(x=>x.bindingId==='mcr2006.fan.flower-tiles'||x.bindingId==='mcr2006.fan.chicken-hand')).toBe(false); expect(r.flowerCount).toBe(8);
 });
 it('distinguishes flower and Kong replacement while preserving Self-Drawn',()=>{
  const flower=base(); flower.context.resolvedWinEvent='flower-replacement'; expect(ids(flower)).toContain('mcr2006.fan.self-drawn'); expect(ids(flower)).not.toContain('mcr2006.fan.out-with-replacement-tile'); const kong=base(); kong.context.resolvedWinEvent='kong-replacement'; expect(ids(kong)).toContain('mcr2006.fan.out-with-replacement-tile'); expect(ids(kong)).toContain('mcr2006.fan.self-drawn');
 });
 it('reconstructs waits globally before assigning an exclusive wait class',()=>{
  const edge:McrScoringInput={evidence:{fixedGroups:[{kind:'chow',exposure:'melded',tiles:[t('dots',1),t('dots',2),t('dots',3)]},{kind:'pung',exposure:'melded',tiles:[t('bamboo',5),t('bamboo',5),t('bamboo',5)]},{kind:'pung',exposure:'melded',tiles:[w('east'),w('east'),w('east')]}],freeTiles:[t('characters',1),t('characters',2),t('dots',7),t('dots',7),t('characters',3)],winningTile:t('characters',3),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}};
  expect(ids(edge)).toContain('mcr2006.fan.edge-wait');
  const closed={...edge,evidence:{...edge.evidence,freeTiles:[t('characters',2),t('characters',4),t('dots',7),t('dots',7),t('characters',3)]}}; expect(ids(closed)).toContain('mcr2006.fan.closed-wait');
  const single:McrScoringInput={evidence:{fixedGroups:[{kind:'chow',exposure:'melded',tiles:[t('characters',1),t('characters',2),t('characters',3)]},{kind:'chow',exposure:'melded',tiles:[t('dots',4),t('dots',5),t('dots',6)]},{kind:'chow',exposure:'melded',tiles:[t('bamboo',7),t('bamboo',8),t('bamboo',9)]},{kind:'pung',exposure:'melded',tiles:[w('east'),w('east'),w('east')]}],freeTiles:[t('dots',7),t('dots',7)],winningTile:t('dots',7),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}}; expect(ids(single)).toContain('mcr2006.fan.single-wait');
 });
 it('fails closed for malformed evidence and surfaces only material trusted wind evidence',()=>{
  const malformed=base(); malformed.evidence.winningTile=t('dots',1); expect(detectMcr2006Fans(malformed).interpretations).toEqual([]); expect(detectMcr2006Fans(base()).missingEvidenceIds).not.toContain('evidence.seat-wind'); const withWind=base(); withWind.evidence.freeTiles=[t('characters',1),t('characters',2),t('characters',3),t('dots',4),t('dots',5),t('dots',6),t('bamboo',7),t('bamboo',8),t('bamboo',9),w('east'),w('east'),w('east'),t('dots',5),t('dots',5)]; withWind.evidence.winningTile=t('dots',5); expect(detectMcr2006Fans(withWind).missingEvidenceIds).toContain('evidence.seat-wind');
 });
 it('treats Last Tile evidence as true, known false, or unknown',()=>{
  const yes=base(); yes.context.lastVisibleCopy=true; expect(ids(yes)).toContain('mcr2006.fan.last-tile'); const no=base(); no.context.lastVisibleCopy=false; expect(ids(no)).not.toContain('mcr2006.fan.last-tile'); expect(detectMcr2006Fans(no).missingEvidenceIds).not.toContain('evidence.last-visible-copy'); const unknown=base(); delete unknown.context.lastVisibleCopy; expect(detectMcr2006Fans(unknown).missingEvidenceIds).toContain('evidence.last-visible-copy');
 });
 it('requires exact suit ownership for terminal Chow fan predicates',()=>{
  const pure=base(); pure.evidence.freeTiles=[t('characters',1),t('characters',2),t('characters',3),t('characters',1),t('characters',2),t('characters',3),t('characters',7),t('characters',8),t('characters',9),t('characters',7),t('characters',8),t('characters',9),t('characters',5),t('characters',5)]; pure.evidence.winningTile=t('characters',5); expect(ids(pure)).toContain('mcr2006.fan.pure-terminal-chows'); const wrongPair={...pure,evidence:{...pure.evidence,freeTiles:[...pure.evidence.freeTiles.slice(0,12),t('dots',5),t('dots',5)],winningTile:t('dots',5)}}; expect(ids(wrongPair)).not.toContain('mcr2006.fan.pure-terminal-chows');
  const three=base(); three.evidence.freeTiles=[t('characters',1),t('characters',2),t('characters',3),t('characters',7),t('characters',8),t('characters',9),t('dots',1),t('dots',2),t('dots',3),t('dots',7),t('dots',8),t('dots',9),t('bamboo',5),t('bamboo',5)]; three.evidence.winningTile=t('bamboo',5); expect(ids(three)).toContain('mcr2006.fan.three-suited-terminal-chows'); const wrongSuit={...three,evidence:{...three.evidence,freeTiles:[...three.evidence.freeTiles.slice(0,12),t('dots',5),t('dots',5)],winningTile:t('dots',5)}}; expect(ids(wrongSuit)).not.toContain('mcr2006.fan.three-suited-terminal-chows');
 });
 it('does not emit direct fan paths without a lawful completion',()=>{
  const bad=base(); bad.evidence.freeTiles=[t('characters',5),t('characters',5),t('characters',5),t('characters',5),t('dots',1),t('dots',4),t('dots',7),t('bamboo',2),t('bamboo',5),t('bamboo',8),t('dots',2),t('dots',5),t('dots',8),t('characters',9)]; bad.evidence.winningTile=t('characters',9); const r=detectMcr2006Fans(bad); expect(r.interpretations).toEqual([]); expect(r.candidates.map(x=>x.bindingId)).not.toEqual(expect.arrayContaining(['mcr2006.fan.tile-hog','mcr2006.fan.knitted-straight','mcr2006.fan.nine-gates']));
 });
 it('canonicalises fixed Chow faces and fixed-group occurrence identities',()=>{
  const input:McrScoringInput={evidence:{fixedGroups:[{kind:'chow',exposure:'melded',tiles:[t('characters',1),t('characters',2),t('characters',3)]},{kind:'chow',exposure:'melded',tiles:[t('dots',1),t('dots',2),t('dots',3)]},{kind:'pung',exposure:'melded',tiles:[w('east'),w('east'),w('east')]}],freeTiles:[t('bamboo',4),t('bamboo',5),t('bamboo',6),t('bamboo',7),t('bamboo',7)],winningTile:t('bamboo',7),flowerCount:0},context:{winSource:'discard',resolvedWinEvent:'none',lastVisibleCopy:false}}; const permuted={...input,evidence:{...input.evidence,fixedGroups:[{...input.evidence.fixedGroups[1]!,tiles:[t('dots',3),t('dots',1),t('dots',2)]},input.evidence.fixedGroups[2]!,{...input.evidence.fixedGroups[0]!,tiles:[t('characters',2),t('characters',3),t('characters',1)]}]}}; const a=detectMcr2006Fans(input),b=detectMcr2006Fans(permuted); expect(a.interpretations.map(x=>x.id)).toEqual(b.interpretations.map(x=>x.id)); expect(a.candidates.map(x=>x.id)).toEqual(b.candidates.map(x=>x.id));
 });
 it('exposes the production MCR evidence-policy seam',()=>{
  expect(MCR_2006_EVIDENCE_POLICY_ID).toBe('evidence-policy.mcr-wmo-2006'); expect(MCR_2006_INPUT_EVIDENCE.validate(base())).toEqual({valid:true}); const unknown=base(); delete unknown.context.lastVisibleCopy; expect(MCR_2006_INPUT_EVIDENCE.requiredEvidence(unknown)).toContain('evidence.last-visible-copy');
 });
});
