import type { ExecutableRegistryIdentity, HandScoreResult, JsonObject, PatternAccumulatorConfigV1, ResolvedProfileArtifact, ScoreDecisionTraceEntry } from './types';

const key = (identity: ExecutableRegistryIdentity) => `${identity.id}@${identity.semanticRevision}`;
/** `id` identifies a matched occurrence; `bindingId` remains the stable source binding. */
export type PatternAccumulatorCandidate = { id: string; value: number; interpretationId: string; bindingId?: string; sourceLocator?: string };
export type PatternAccumulatorSuppressedCandidate = { candidate: PatternAccumulatorCandidate; reasonId: string };
export type PatternAccumulatorInteraction = { counted: readonly PatternAccumulatorCandidate[]; suppressed: readonly PatternAccumulatorSuppressedCandidate[] };
export type PatternAccumulatorInterpretation = { id: string; candidates: readonly PatternAccumulatorCandidate[] };
export type PatternAccumulatorInputCheck = { valid: true } | { valid: false; reasonId: string };

/** Code-owned signatures: profile JSON selects exact identities, never callbacks. */
export type PatternAccumulatorStageContracts<TInput> = {
  inputEvidence: { validate: (input: TInput) => PatternAccumulatorInputCheck; requiredEvidence: (input: TInput) => readonly string[] };
  catalogue: (input: TInput) => readonly PatternAccumulatorCandidate[];
  interaction: (candidates: readonly PatternAccumulatorCandidate[]) => PatternAccumulatorInteraction;
  interpretation: (candidates: readonly PatternAccumulatorCandidate[]) => PatternAccumulatorInterpretation;
  qualification: (subtotal: number) => string | undefined;
  postQualificationBonus?: (input: TInput) => number;
  conversion?: (value: number) => number;
};
export type PatternAccumulatorImplementationBank<TInput> = {
  resultProvenance: { kind: string };
  inputEvidence: ReadonlyMap<string, PatternAccumulatorStageContracts<TInput>['inputEvidence']>;
  catalogue: ReadonlyMap<string, PatternAccumulatorStageContracts<TInput>['catalogue']>;
  interaction: ReadonlyMap<string, PatternAccumulatorStageContracts<TInput>['interaction']>;
  interpretation: ReadonlyMap<string, PatternAccumulatorStageContracts<TInput>['interpretation']>;
  qualification: ReadonlyMap<string, PatternAccumulatorStageContracts<TInput>['qualification']>;
  postQualificationBonus: ReadonlyMap<string, NonNullable<PatternAccumulatorStageContracts<TInput>['postQualificationBonus']>>;
  conversion: ReadonlyMap<string, NonNullable<PatternAccumulatorStageContracts<TInput>['conversion']>>;
};
type I = { catalogue: ExecutableRegistryIdentity; evidencePolicy: ExecutableRegistryIdentity; interaction: ExecutableRegistryIdentity; interpretation: ExecutableRegistryIdentity; qualification: ExecutableRegistryIdentity; postQualificationBonus?: ExecutableRegistryIdentity; conversion?: ExecutableRegistryIdentity };
const dependency = (artifact: ResolvedProfileArtifact, id: string) => { const found = artifact.executableDependencies.find((item) => item.id === id); if (!found) throw Error(`HAND_SCORER_DEPENDENCY_UNAVAILABLE:${id}`); return found; };
const get = <T>(bank: ReadonlyMap<string, T>, identity: ExecutableRegistryIdentity, stage: string): T => { const found = bank.get(key(identity)); if (!found) throw Error(`PATTERN_ACCUMULATOR_IMPLEMENTATION_UNAVAILABLE:${stage}:${key(identity)}`); return found; };

export const compilePatternAccumulatorHandScorer = <TInput>(artifact: ResolvedProfileArtifact, bank: PatternAccumulatorImplementationBank<TInput>) => {
  if (artifact.profile.scoring.grammar !== 'pattern-accumulator') throw Error(`HAND_SCORER_GRAMMAR_UNSUPPORTED:${artifact.profile.scoring.grammar}`);
  const config: PatternAccumulatorConfigV1 = artifact.profile.scoring.config;
  if (config.floorPolicyId || config.capPolicyId) throw Error(`PATTERN_ACCUMULATOR_POLICY_UNSUPPORTED:${config.floorPolicyId ?? config.capPolicyId}`);
  if (artifact.profile.evidence.policyIds.length !== 1) throw Error('PATTERN_ACCUMULATOR_EVIDENCE_POLICIES_UNSUPPORTED');
  const ids: I = { catalogue: dependency(artifact, config.patternCatalogueId), evidencePolicy: dependency(artifact, artifact.profile.evidence.policyIds[0]!), interaction: dependency(artifact, config.interactionPolicyId), interpretation: dependency(artifact, config.interpretationPolicyId), qualification: dependency(artifact, config.qualificationPolicyId), ...(config.postQualificationBonusPolicyId ? { postQualificationBonus: dependency(artifact, config.postQualificationBonusPolicyId) } : {}), ...(config.conversionPolicyId ? { conversion: dependency(artifact, config.conversionPolicyId) } : {}) };
  const inputEvidence = get(bank.inputEvidence, ids.evidencePolicy, 'evidence-policy'); const catalogue = get(bank.catalogue, ids.catalogue, 'catalogue'); const interaction = get(bank.interaction, ids.interaction, 'interaction'); const interpretation = get(bank.interpretation, ids.interpretation, 'interpretation'); const qualification = get(bank.qualification, ids.qualification, 'qualification'); const bonus = ids.postQualificationBonus ? get(bank.postQualificationBonus, ids.postQualificationBonus, 'post-qualification-bonus') : () => 0; const conversion = ids.conversion ? get(bank.conversion, ids.conversion, 'conversion') : (value: number) => value;
  return (input: TInput): HandScoreResult => {
    const trace: ScoreDecisionTraceEntry[] = [];
    const finish = (disposition: HandScoreResult['disposition'], total: number, details: JsonObject): HandScoreResult => ({ grammar: 'pattern-accumulator', profile: { id: artifact.profile.identity.id, version: artifact.profile.identity.version }, rulesFingerprint: artifact.rulesFingerprint, legal: disposition.kind === 'scored', disposition, explanation: [], decisionTrace: trace, matchedCanonicalPatternIds: [], result: { unit: config.unit, total, details } });
    const check = inputEvidence.validate(input); if (!check.valid) return finish({ kind: 'invalid', reasonId: check.reasonId }, 0, {});
    const missing = inputEvidence.requiredEvidence(input); trace.push({ id: 'evidence:resolved', kind: 'stage', identities: { policyId: key(ids.evidencePolicy) }, metadata: { missingEvidenceIds: [...missing] } }); if (missing.length) return finish({ kind: 'needs-evidence', missingEvidenceIds: missing }, 0, {});
    const candidates = catalogue(input); const candidateDetails = candidates.map(({ id, value, bindingId, sourceLocator }) => ({ id, value, ...(bindingId ? { bindingId } : {}), ...(sourceLocator ? { sourceLocator } : {}) })); candidates.forEach((candidate) => trace.push({ id: `candidate:${candidate.id}`, kind: 'candidate', identities: { ruleId: candidate.id, ...(candidate.bindingId ? { bindingId: candidate.bindingId } : {}), sourceId: key(ids.catalogue) }, metadata: { value: candidate.value, ...(candidate.sourceLocator ? { sourceLocator: candidate.sourceLocator } : {}) } }));
    const lawful = interaction(candidates); const suppressed = lawful.suppressed.map(({ candidate, reasonId }) => ({ id: candidate.id, value: candidate.value, reasonId })); lawful.suppressed.forEach(({ candidate, reasonId }) => trace.push({ id: `suppressed:${candidate.id}`, kind: 'suppress', identities: { ruleId: candidate.id, policyId: key(ids.interaction), reasonId }, metadata: { value: candidate.value } }));
    const chosen = interpretation(lawful.counted); const counted = chosen.candidates.map(({ id, value }) => ({ id, value })); trace.push({ id: 'interpretation:selected', kind: 'select', identities: { policyId: key(ids.interpretation), ruleId: chosen.id } }); chosen.candidates.forEach((candidate) => trace.push({ id: `counted:${candidate.id}`, kind: 'count', identities: { ruleId: candidate.id }, metadata: { value: candidate.value } }));
    const subtotal = chosen.candidates.reduce((total, candidate) => total + candidate.value, 0); const reason = qualification(subtotal); trace.push({ id: 'qualification:decision', kind: 'stage', identities: { policyId: key(ids.qualification), reasonId: reason ?? 'qualification.passed' }, metadata: { qualifyingSubtotal: subtotal } }); const details = { candidatePatterns: candidateDetails, countedPatterns: counted, suppressedPatterns: suppressed, selectedInterpretationId: chosen.id, qualifyingSubtotal: subtotal }; if (reason) return finish({ kind: 'not-qualifying', reasonId: reason }, 0, { ...details, postQualificationBonus: 0 });
    const extra = bonus(input); if (ids.postQualificationBonus) trace.push({ id: 'bonus:post-qualification', kind: 'stage', identities: { policyId: key(ids.postQualificationBonus) }, metadata: { value: extra } }); const total = conversion(subtotal + extra); if (ids.conversion) trace.push({ id: 'conversion:final', kind: 'final', identities: { policyId: key(ids.conversion) }, metadata: { input: subtotal + extra, total } }); return finish({ kind: 'scored' }, total, { ...details, postQualificationBonus: extra, finalValue: total, provenance: { ...bank.resultProvenance, executableDependencies: Object.values(ids).filter(Boolean).map(key) } });
  };
};

export type PatternAccumulatorProofInput = { structurallyValid: boolean; detectedFacts: readonly ('ordinary-three' | 'ordinary-four' | 'ordinary-eight' | 'ordinary-nine' | 'suppression-target')[]; knownEvidenceIds: readonly string[]; requiresResolvedWinEvent?: boolean; flowerCount: number };
export const PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES: I = { catalogue: { id: 'catalogue.pattern.a0-proof', semanticRevision: 1 }, evidencePolicy: { id: 'evidence-policy.a0-proof', semanticRevision: 1 }, interaction: { id: 'interaction.a0-proof-highest-only', semanticRevision: 1 }, interpretation: { id: 'interpretation.a0-proof-highest-lawful', semanticRevision: 1 }, qualification: { id: 'qualification.a0-proof-eight-before-flowers', semanticRevision: 1 }, postQualificationBonus: { id: 'post-qualification-bonus.a0-proof-flowers', semanticRevision: 1 }, conversion: { id: 'conversion.a0-proof-identity', semanticRevision: 1 } };
const a0Candidate = (input: PatternAccumulatorProofInput): readonly PatternAccumulatorCandidate[] => input.detectedFacts.map((fact) => ({ 'ordinary-three': { id: 'proof.ordinary-three', value: 3, interpretationId: 'default' }, 'ordinary-four': { id: 'proof.ordinary-four', value: 4, interpretationId: 'default' }, 'ordinary-eight': { id: 'proof.ordinary-eight', value: 8, interpretationId: 'default' }, 'ordinary-nine': { id: 'proof.ordinary-nine', value: 9, interpretationId: 'high' }, 'suppression-target': { id: 'proof.suppression-target', value: 4, interpretationId: 'high' } }[fact]));
export const PATTERN_ACCUMULATOR_A0_PROOF_BANK: PatternAccumulatorImplementationBank<PatternAccumulatorProofInput> = { resultProvenance: { kind: 'non-production-a0-proof' }, inputEvidence: new Map([[key(PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES.evidencePolicy), { validate: (input) => !input.structurallyValid || !Number.isInteger(input.flowerCount) || input.flowerCount < 0 ? { valid: false, reasonId: 'pattern-accumulator.a0-proof.invalid-input' } : { valid: true }, requiredEvidence: (input) => input.requiresResolvedWinEvent && !input.knownEvidenceIds.includes('evidence.resolved-win-event') ? ['evidence.resolved-win-event'] : [] }]]), catalogue: new Map([[key(PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES.catalogue), a0Candidate]]), interaction: new Map([[key(PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES.interaction), (candidates) => ({ counted: candidates.filter((candidate) => candidate.id !== 'proof.suppression-target'), suppressed: candidates.filter((candidate) => candidate.id === 'proof.suppression-target').map((candidate) => ({ candidate, reasonId: 'interaction.a0-proof.highest-only' })) })]]), interpretation: new Map([[key(PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES.interpretation), (candidates) => [...new Set(candidates.map((candidate) => candidate.interpretationId))].map((id) => ({ id, candidates: candidates.filter((candidate) => candidate.interpretationId === id) })).sort((left, right) => right.candidates.reduce((total, candidate) => total + candidate.value, 0) - left.candidates.reduce((total, candidate) => total + candidate.value, 0) || left.id.localeCompare(right.id))[0] ?? { id: 'default', candidates: [] }]]), qualification: new Map([[key(PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES.qualification), (subtotal) => subtotal >= 8 ? undefined : 'qualification.a0-proof.eight-before-flowers']]), postQualificationBonus: new Map([[key(PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES.postQualificationBonus!), (input) => input.flowerCount]]), conversion: new Map([[key(PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES.conversion!), (value) => value]]) };
export const compileA0ProofPatternAccumulatorHandScorer = (artifact: ResolvedProfileArtifact) => compilePatternAccumulatorHandScorer(artifact, PATTERN_ACCUMULATOR_A0_PROOF_BANK);
export const compileHandScorer = compileA0ProofPatternAccumulatorHandScorer;
