import { describe, expect, it } from 'vitest';
import { compileHandScorer, PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES } from './pattern-accumulator-runtime';
import type { PatternAccumulatorConfigV1, ResolvedProfileArtifact } from './types';

it('fails closed when a second evidence policy is configured', () => {
  const profile = artifact();
  profile.profile.evidence = { ...profile.profile.evidence, policyIds: ['evidence-policy.a0-proof', 'evidence-policy.second'] };
  expect(() => compileHandScorer(profile)).toThrow('EVIDENCE_POLICIES_UNSUPPORTED');
});
const artifact=():ResolvedProfileArtifact=>({profile:{schemaVersion:1,identity:{id:'proof.pattern-accumulator-a0',version:'0.0.1',status:'provisional',familyId:'family.proof',grammar:'pattern-accumulator'},table:{playerCount:4,seatModelId:'seats.proof'},tileSet:{presetId:'tiles.proof',options:{}},handShape:{presetId:'shape.proof',options:{}},validation:{handShapePolicyId:'validation.proof',policyIds:[]},scoring:{grammar:'pattern-accumulator',config:{configVersion:1,unit:'points',patternCatalogueId:'catalogue.pattern.a0-proof',interactionPolicyId:'interaction.a0-proof-highest-only',qualificationPolicyId:'qualification.a0-proof-eight-before-flowers',interpretationPolicyId:'interpretation.a0-proof-highest-lawful',postQualificationBonusPolicyId:'post-qualification-bonus.a0-proof-flowers',conversionPolicyId:'conversion.a0-proof-identity'}},evidence:{policyIds:['evidence-policy.a0-proof'],alwaysRequired:[]},settlement:{id:'settlement.unfinished',params:{}},progression:{id:'progression.unfinished',params:{}},gameEnd:{id:'game-end.unfinished',params:{}},provenance:{}},rulesFingerprint:'proof',executableDependencies:Object.values(PATTERN_ACCUMULATOR_A0_PROOF_IDENTITIES).filter(Boolean)});
describe('pattern accumulator banks',()=>{const total=(r:ReturnType<ReturnType<typeof compileHandScorer>>)=>(r.result as {total:number}).total;it('dispatches exact proof implementations and fails closed',()=>{const bad=artifact();bad.executableDependencies=bad.executableDependencies.map(x=>x.id==='catalogue.pattern.a0-proof'?{...x,semanticRevision:2}:x);expect(()=>compileHandScorer(bad)).toThrow('IMPLEMENTATION_UNAVAILABLE');expect(()=>compileHandScorer(artifact())).not.toThrow()});it('catalogue detects candidates and evidence policy owns unresolved facts',()=>{const s=compileHandScorer(artifact());expect(total(s({structurallyValid:true,detectedFacts:['ordinary-eight'],flowerCount:2,knownEvidenceIds:[]}))).toBe(10);expect(s({structurallyValid:true,detectedFacts:['ordinary-eight'],flowerCount:0,knownEvidenceIds:[],requiresResolvedWinEvent:true}).disposition).toEqual({kind:'needs-evidence',missingEvidenceIds:['evidence.resolved-win-event']});expect(s({structurallyValid:false,detectedFacts:[],flowerCount:0,knownEvidenceIds:[]}).disposition.kind).toBe('invalid')});it('keeps A0 order and suppression',()=>{const s=compileHandScorer(artifact());expect(s({structurallyValid:true,detectedFacts:['ordinary-three','ordinary-four'],flowerCount:2,knownEvidenceIds:[]}).disposition.kind).toBe('not-qualifying');const r=s({structurallyValid:true,detectedFacts:['ordinary-eight','ordinary-nine','suppression-target'],flowerCount:0,knownEvidenceIds:[]});expect(total(r)).toBe(9);expect(r.decisionTrace.some(x=>x.kind==='suppress')).toBe(true)});it('is safe without optional bonus/conversion and rejects ignored policies',()=>{const a=artifact();const c=a.profile.scoring.config as PatternAccumulatorConfigV1;a.profile.scoring={grammar:'pattern-accumulator',config:{...c,postQualificationBonusPolicyId:undefined,conversionPolicyId:undefined}};expect(total(compileHandScorer(a)({structurallyValid:true,detectedFacts:['ordinary-eight'],flowerCount:2,knownEvidenceIds:[]}))).toBe(8);const b=artifact();b.profile.scoring={grammar:'pattern-accumulator',config:{...(b.profile.scoring.config as PatternAccumulatorConfigV1),capPolicyId:'value-policy.unimplemented'}};expect(()=>compileHandScorer(b)).toThrow('POLICY_UNSUPPORTED')});it('never accepts canonical MCR identity',()=>{const a=artifact();a.profile.scoring={grammar:'pattern-accumulator',config:{...(a.profile.scoring.config as PatternAccumulatorConfigV1),patternCatalogueId:'catalogue.pattern.mcr-wmo-2006'}};expect(()=>compileHandScorer(a)).toThrow('DEPENDENCY_UNAVAILABLE')})});
