import { ArrowRight, BookOpen, Calculator, Wrench } from 'lucide-react';
import { SiteHeader } from '../components/SiteHeader';
import { ReturnToGame } from '../components/ReturnToGame';
import { scoreHand } from '../scoring';
import { TileStrip } from './MahjongTileGallery';
import { completedExampleHref, practiceExampleHref, scoringExampleBonusTiles, scoringExampleContext, scoringExamples, scoringExampleTiles } from './scoring-examples';

function ResultSummary({ result }: { result: ReturnType<typeof scoreHand> }) {
  if (result.scoringMode === 'standard') return <><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div><b className="block font-serif text-xl">{result.basePoints}</b><span className="text-[9px] text-[#66746e]">points</span></div><div><b className="block font-serif text-xl">{result.doubles}</b><span className="text-[9px] text-[#66746e]">doubles</span></div><div><b className="block font-serif text-xl">{result.finalScore}</b><span className="text-[9px] text-[#66746e]">total</span></div></div><p className="mt-4 text-[10px] leading-5 text-[#66746e]">Ordinary points and doubles are itemised in the scorer.</p></>;
  return <><div className="mt-3 space-y-2">{result.calculationComponents.map((component) => <div key={component.id} className="rounded-md bg-[#eee6d5] p-2 text-[10px] leading-4"><b className="block text-[#284d45]">{component.label} · {component.subtotal}</b><span className="text-[#66746e]">{component.base} points{component.doubles ? ` × ${2 ** component.doubles} (${component.doubles} double${component.doubles === 1 ? '' : 's'})` : ' fixed'}</span></div>)}</div><div className="mt-3 text-center"><b className="font-serif text-xl">{result.finalScore}</b><span className="ml-1 text-[9px] text-[#66746e]">total</span></div><p className="mt-3 text-[10px] leading-5 text-[#66746e]">Components keep fixed special/fishing values separate from any bonus-tile doubles.</p></>;
}

export function ScoringExamplesPage() {
  return <div className="min-h-screen bg-[#f5f1e6] text-[#284d45]"><SiteHeader />
    <main className="mx-auto max-w-5xl px-5 py-8 sm:px-8 sm:py-12">
      <ReturnToGame />
      <div className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#ae6249]">Learn by a real calculation</p><h1 className="mt-3 font-serif text-[clamp(38px,7vw,64px)] leading-[.95] tracking-[-.035em]">British Mahjong<br/><span className="text-[#ae6249]">scoring examples.</span></h1><p className="mt-5 text-[15px] leading-7 text-[#66746e]">Six compact, worked hands chosen to explain a different scoring decision. Every result below is calculated from the same hand data used by the scorer—then you can open it complete or build it yourself.</p></div>
      <div className="mt-8 rounded-xl border border-[#b8cdbf] bg-[#edf3ed] p-4 text-[12px] leading-6 text-[#284d45]"><BookOpen size={16} className="mr-2 inline text-[#477562]"/>Want a blank calculator instead? <a className="font-semibold underline decoration-[#ae6249] underline-offset-4" href="/hand">Open the British Mahjong hand scorer</a>. These examples link to the <a className="font-semibold underline decoration-[#ae6249] underline-offset-4" href="/guide#ordinary-scoring">scoring guide</a> and the <a className="font-semibold underline decoration-[#ae6249] underline-offset-4" href="/special-hands">special-hand catalogue</a> where useful.</div>
      <div className="mt-10 space-y-6">{scoringExamples.map((example, index) => {
        const result = scoreHand(example.hand, example.context);
        return <article id={example.id} key={example.id} className="scroll-mt-6 rounded-2xl border border-[#d8ceb8] bg-[#fbf8ed] p-5 shadow-[var(--shadow-sm)] sm:p-7"><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_15rem]"><div className="min-w-0"><div className="font-mono text-[10px] uppercase tracking-[.18em] text-[#ae6249]">Example {String(index + 1).padStart(2, '0')}</div><h2 className="mt-2 font-serif text-[28px] leading-tight">{example.title}</h2><p className="mt-2 text-[13px] leading-6 text-[#66746e]">{example.purpose}</p><div className="mt-5"><TileStrip tiles={scoringExampleTiles(example)} ariaLabel={`${example.title} tiles`} /></div>{scoringExampleBonusTiles(example).length > 0 && <div className="mt-3"><div className="font-mono text-[9px] uppercase tracking-[.14em] text-[#ae6249]">Bonus tiles</div><TileStrip tiles={scoringExampleBonusTiles(example)} ariaLabel={`${example.title} bonus tiles`} /></div>}<div className="mt-5 grid gap-2 text-[11px] sm:grid-cols-3"><div className="rounded-md bg-[#f2ecdf] p-3"><b>Context</b><br/>{example.context.playerWind} player · {example.context.prevailingWind} prevailing</div><div className="rounded-md bg-[#f2ecdf] p-3"><b>Outcome</b><br/>{example.hand.isWinner ? 'Winning hand' : 'Not a winner'} · {result.evidenceCompleteness} evidence</div><div className="rounded-md bg-[#f2ecdf] p-3"><b>Structure</b><br/>{example.hand.sets.some((set) => set.visibility === 'exposed') ? 'Includes exposed sets' : 'Concealed / loose-tile layout'}</div></div><p className="mt-5 text-[12px] leading-6 text-[#66746e]">{example.explanation}</p><p className="mt-3 text-[11px] text-[#66746e]">{example.references.map((reference, i) => <span key={reference.href}>{i > 0 && ' · '}<a className="font-semibold underline decoration-[#ae6249] underline-offset-4" href={reference.href}>{reference.label}</a></span>)}</p></div><aside className="rounded-xl border border-[#d8ceb8] bg-[#f5f1e6] p-4"><div className="font-mono text-[9px] uppercase tracking-[.16em] text-[#ae6249]">Real scorer result</div><ResultSummary result={result} /><div className="mt-5 space-y-2"><a href={completedExampleHref(example.id)} className="flex min-h-11 items-center justify-center gap-2 rounded-md bg-[#284d45] px-3 text-center text-[11px] font-semibold text-[#f8f4e9]"><Calculator size={14}/>Open in scorer</a>{example.practice && <a href={practiceExampleHref(example.id)} className="flex min-h-11 items-center justify-center gap-2 rounded-md border border-[#b8cdbf] bg-[#edf3ed] px-3 text-center text-[11px] font-semibold"><Wrench size={14}/>Build it yourself</a>}</div></aside></div></article>;
      })}</div>
      <div className="mt-10"><a href="/hand" className="inline-flex min-h-11 items-center gap-2 rounded-md border border-[#c9b99d] bg-[#fdfbf5] px-4 text-[12px] font-semibold">Try another hand <ArrowRight size={14}/></a></div>
    </main></div>;
}
